### ISSUE TITLE
Paperback extension

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1153]
Build an extension to support [Paperback](https://paperback.moe/)

**Comment by JohnKacz** [comment]
Is this meant to be [Paperback](https://paperback.moe/) extension. I saw Paperback support was listed on the description of the [v0.5.3 - UX Refresh](https://github.com/Kareadita/Kavita/projects/26) project but didn't see an issue or card for it. 

If so is there any support the community could offer? I ask because I just got into the most recent round of Testflight invites :)

**Comment by majora2007** [comment]
Oh yeah, it is supposed to be Paperback, @JohnKacz. I must have misspelled it when I was creating the issue. 

If you are willing to help, I would appreciate it. I currently have it on the backlog as a low priority item.

**Comment by majora2007** [comment]
This is finally done
https://wiki.kavitareader.com/en/guides/misc/paperback
