### ISSUE TITLE
Email Functionality Feedback

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1237]
After rolling out email functionality, many users seem to not enjoy the functionality. I personally love the forgot user flow, however I think there may be a different way to approach the login service.

The goal of implementing email functionality was:
1. A way for users to email books to themselves for Kindle or device reading
2. The ability to quickly invite users rather than create user accounts
3. Allow any user to reset their password without bothering the admin.

What I have learned after the fact:
1. Kindle users have a special email that is linked to their account and is not bound to their actual email.
2. Users do not trust open source solutions with their email.
3. Forgot User flow can work without email.

Looking towards a different solution, I can use a Request system instead for the flow.

We will still use confirmation links but without an email account. To create a new user, like the current system, we will generate a temp user and a link for a user to sign up with. The admin is responsible to fill it out to complete registration or send it to a user to perform registration.

For forgot password, we can send a Request to the admin in their server settings (new section) for the admin to approve the request and issue a new url for the user (or reset for the user on their behalf). This view and functionality will be added with a new RBS Role, so users can manage in place of the admin. Likewise, the url for resetting will be dropped into the logs, so an admin can forgot user their own account.

Lastly, for kindle users, we will just expose an email for send books as a setting on their user profile, not tied to main account creation. 

This is my initial idea to revamp the system. I would love comments and feedback from the community before I move forward with this.

**Comment by earth4s** [comment]
I like idea for the Request system but I have some recommendations:

1) The option to use SMTP for email. This will allow admins to use a domain they control (probably the same domain they host kavita on) in their email. You can make it optional so admins can chose if they want to use their own email or the current email system. 

2) I think the web admin password reset should be done via command line. Pihole has a good implementation of this in their software. The command "Pihole -a -p" is use to reset the web admin password. "-a" being admin console fuction and "-p" being for passwords.
More info: https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738

3) The user registration email like that the admin generates should be handled two ways. 

   - The first like you said where the admin has to created the account fully, like Active Directory. 
   - The second is when the admin generates the request it will create a blank temp account. So when the user access the link (either via email or link provided by the admin) it will have them fill out the information.

**Comment by majora2007** [comment]
Thanks for providing some input. 

For 1, we already provide that out of the box. It's a secondary image you can run on your PC with your own SMTP server. We have documentation and everything for it. Seems no one knows about it.

For 2, no comment. 

For 3, that's how it works now as well.

**Comment by InvisCo** [comment]
I agree with making the SMTP container more noticeable. I think some mention of it should be added to the documentation around the initial setup and/or the docker setup steps.

I had not updated from version 5.0.0 until last week because I did not wish to have the emails routed through your servers. I only stumbled across the KavitaEmail repository accidentally when I clicked on the Kareadita profile instead of the Kavita repository.

**Comment by ThePromidius** [comment]
I might be totally wrong with what I'm going to say. If so i apologize.
One of the reasons SMPT isn't that well know is because it was a thing that happened on the go. Idk if Joe posted it anywhere outside discord but it was a hot topic there. And even then people still didn't know about it.

I'll add as well that this feedback thread should have been created earlier. This topic has been left untouched too long.

I sincerely hope that feedback is taken into account before the next big update. Maybe not add all the functionality but a change in some aspects is needed asap. Specially for new users.

Regarding smpt documentation. It's not that well documented even on the wiki. There's only one article in the faq. There was an attempt to create a dedicated page for it but there was not enough content

**Comment by majora2007** [comment]
Yes, I should have created email feedback earlier, however, I wanted to let it sit and see how people like it or not after the initial knee jerk of change. 

I have started to add documentation in the initial create user flow, to help the admins understand that email doesn't need to be real (although forgot password flow wont work), you can user your own email service, etc. 

I have also updated the flow to make it really easy to just create a local user, it generates a link, you click it and finish setting up the invited user, like the old flow, just with an email being needed (again can be junk). 

I will update the documentation and also provide links to the wiki from within Kavita itself in multiple places to help people understand.

Based on feedback from discord, more people actually enjoy the integration but def can see a lack of knowledge on the ability to use your own email service. 

Please keep the feedback coming. I just wanted to provide an update on what I've done since some of the feedback has started to pour in.

**Comment by majora2007** [comment]
As promised, here is a better wiki article:
https://wiki.kavitareader.com/en/guides/misc/email

**Comment by DarkVirtue** [comment]
I've spent the last couple of days playing around with Kavita and have some feedback on the email system.

First, this feels like a really bizarre way to handle email for the application. No other self-hosted service I've used defaults to using a second- or third-party email service. The conventional method for configuring email is to expose the SMTP settings directly. This feels doubly strange since the KavitaEmail project exists - is there some reason that application can't be directly integrated?

There's no mention of the KavitaEmail project anywhere on the GitHub page of Kavita, or anywhere in the documentation outside of that tiny little article buried in the Misc Guides section of the wiki. I feel disclosure about Kavita's default behavior of routing email through your service needs to be much more visible. For example, in the installation instructions for Kavita and on the Email settings page within Kavita should directly reference KavitaEmail and how to set it up. Ideally, it should be an opt-in option rather than requiring the user to opt out by installing and configuring the KavitaEmail proxy. It almost feels like the Kavita project is keeping this info out of sight in the hopes users won't notice and just use the default email service, which is not a good look.

I also have concerns about the Kavita email service itself.
* From what I've read in this issue and a couple of others, the Kavita Email Service is just a Gmail account? I don't have Google's Terms of Service in front of me, but is that allowed?
*  Aren't there some pretty serious liability concerns?
* What if someone tries to send spam using the mail protocol in Kavita?
* What if a Kavita user is sending invites to their Kavita instance that contains illlegal content, like child porn? The Kavita email service could potentially be subpoenaed.
* The mail config page claims emails sent through your service are deleted immediately - can you prove that? Could you prove it to a lawyer, if you had to?
* What about email metadata? Are recipients of mails sent through the service added to the service's internal contacts?

**Comment by majora2007** [comment]
This has been implemented with changes outlined here:
https://github.com/Kareadita/Kavita/pull/1567

Thank you for your feedback. This change should satisfy those of you who do not want to expose their email and those who don't care and what the forgot password functionality (even though prior could have this by setting up their own email service).

**Comment by Kyle-B** [comment]
Fairly late, but as someone that is installing things fresh - I do agree with the comments that it's a bit odd compared to most other apps to need to setup another process for just for sending via my own SMTP server. It's a bit of a hassle to have to run yet another service, I'd much rather just put my SMTP settings into Kavita if possible, and not need to setup/maintain/run KavitaEmail as well.

**Comment by HammyHavoc** [comment]
> Fairly late, but as someone that is installing things fresh - I do agree with the comments that it's a bit odd compared to most other apps to need to setup another process for just for sending via my own SMTP server. It's a bit of a hassle to have to run yet another service, I'd much rather just put my SMTP settings into Kavita if possible, and not need to setup/maintain/run KavitaEmail as well.

Yes, whilst it works, it just seems messy versus having SMTP capabilities built straight into the container. It's very strange that it defaults to a third-party email service.

**Comment by majora2007** [comment]
> > Fairly late, but as someone that is installing things fresh - I do agree with the comments that it's a bit odd compared to most other apps to need to setup another process for just for sending via my own SMTP server. It's a bit of a hassle to have to run yet another service, I'd much rather just put my SMTP settings into Kavita if possible, and not need to setup/maintain/run KavitaEmail as well.
> 
> Yes, whilst it works, it just seems messy versus having SMTP capabilities built straight into the container. It's very strange that it defaults to a third-party email service.

This is because if I didn't, if you wanted to use forgot password or all those other features out of the box, you couldn't without setting up your own SMTP server. By having it separated, many users benefit from the out of the box email services. 

Do note, this issue is closed. I am no longer looking for feedback from the community (given it's been out for over a year now).

**Comment by HammyHavoc** [comment]
> > > Fairly late, but as someone that is installing things fresh - I do agree with the comments that it's a bit odd compared to most other apps to need to setup another process for just for sending via my own SMTP server. It's a bit of a hassle to have to run yet another service, I'd much rather just put my SMTP settings into Kavita if possible, and not need to setup/maintain/run KavitaEmail as well.
> > 
> > 
> > Yes, whilst it works, it just seems messy versus having SMTP capabilities built straight into the container. It's very strange that it defaults to a third-party email service.
> 
> This is because if I didn't, if you wanted to use forgot password or all those other features out of the box, you couldn't without setting up your own SMTP server. By having it separated, many users benefit from the out of the box email services.
> 
> Do note, this issue is closed. I am no longer looking for feedback from the community (given it's been out for over a year now).

Whilst that's fair enough to not want further feedback, I still feel it's a matter worthy of consideration in the present. Do note that almost every other project available doesn't have functioning "forgot my password" until SMTP is set up, and it's absolutely the norm.

**Comment by johnmmcgee** [comment]
It does seem odd that the smtp portion is not built into the application itself.
