### ISSUE TITLE
Ebook structure for anime novels with many independent specials

### ISSUE THREAD

**Issue by zFerry98** [Kareadita/Kavita#1385]
I don't know how to manage such a case:
![image](https://user-images.githubusercontent.com/17975351/179858686-ae20458d-700f-4afa-9bec-156407cc681d.png)
![image](https://user-images.githubusercontent.com/17975351/179858750-7229ddc8-2b02-4b62-af67-4b8d49f21bc8.png)

![image](https://user-images.githubusercontent.com/17975351/179858800-635ba377-e681-4947-9e0b-205c1c59e82a.png)
![image](https://user-images.githubusercontent.com/17975351/179858853-56f20fc9-d30f-4e00-b1b6-0230013ff725.png)

As you can see from the screenshots, this series has a boatload of Special (but independent) without numbering.
The result would be to see a series called "A Certain Magical Index (Side Stories)" with all those novels in it (instead of seeing them as standalone series in the library).

In the Wiki, on eBooks there are no strottures to follow, and those of manga comics force you to give a global name to all files (like: "Global Title - v1 - 'original file title'".
Thanks in advance for the clarifications

**Comment by majora2007** [comment]
For these epubs, are you against the idea of having a "Series of A Certain Magical Index (Parody)"? Then from the main series, you can link this whole series as a Side Story (Series Relationships). 

Then inside, each one can be given an arbitrary order inside the series with it's own title. I think that would be the best way to approach it (btw epubs don't care about filenames). 

Otherwise, having them each as their own entity is a solution and using Series Relationships to keep them all linked to the main Series would work, although a bit messy. 

Let me know your thoughts.

**Comment by zFerry98** [comment]
> For these epubs, are you against the idea of having a "Series of A Certain Magical Index (Parody)"?

No, it is the result I would like to obtain, a single series in the main page of the library called "A Certain Magical Index (Side Stories)" with those epub files inside.
The problem is that even changing the file name (as you will see below) is not considered.

Of that feature you say (relationships), does it take the extra 50 sets off my main library and end up in the series SPs I used for relationships?

I tried to do this:
![image](https://user-images.githubusercontent.com/17975351/179860603-3697460a-bd76-4cbd-b127-5df91372ffd2.png)
# Result:
![image](https://user-images.githubusercontent.com/17975351/179860586-7d18b656-17b5-4004-97b6-f174b2159040.png)
Ignore filenames.

**Comment by zFerry98** [comment]
Another example are the Monogatari series, the novels have the names "Bake, Kizu etc". They are put on as separate series instead of inside Monogatari.
![image](https://user-images.githubusercontent.com/17975351/179862083-084e9b33-ca3d-4625-826b-e9deaff705f3.png)
![image](https://user-images.githubusercontent.com/17975351/179862157-f5a2f248-215b-448e-a2df-143e087e4a74.png)

I don't understand how to make them one series (since the filename is ignored).
Thanks again (if I don't answer it's because it's 01:00 from me).

**Comment by majora2007** [comment]
Okay then we are thinking the same thing. Filenames are not used for epub parsing, it's only the internal metadata of the epub. 

We have a wiki guide for you, this is what you'll need to do:
https://wiki.kavitareader.com/en/guides/managing-your-files/ebooks

Using calibre:series and calibre:series_index, you can group them into a series of "A Certain Magical Index (Parody)" with the arbitrarily order. Just make sure you also set their Title so that you can see the title (like in Card layout):

![image](https://user-images.githubusercontent.com/735851/179862350-9c0b8401-d245-458b-9646-4281453fff59.png)
![image](https://user-images.githubusercontent.com/735851/179862423-8e060008-56c7-4d90-84a7-39c401349fc1.png)

**Comment by zFerry98** [comment]
Ok, now i understand, thanks.
