### ISSUE TITLE
login not working on ipad

### ISSUE THREAD

**Issue by HerrFrutti** [Kareadita/Kavita#1475]
I'm having the problem, that I can't login on my Ipad 9 (15.6.1). Safari Browser works, but brave and opera browser... don't know what happens there.
This message pops up when first loading the page.
![IMG_0007](https://user-images.githubusercontent.com/6975702/186591903-618664a0-ff98-4dde-9070-6beaf9811311.jpeg)
And after trying to login, this message pops up:
![IMG_0006](https://user-images.githubusercontent.com/6975702/186591929-1a25daae-5aa0-445f-98d4-38ec40f2273a.jpeg)
If you need any thing let me know.
thanks :)

**Comment by majora2007** [comment]
This was validated as working. So next release you will get your fix.

**Comment by HerrFrutti** [comment]
should this be fixed with the last release? Because I'm still having this issue...

**Comment by majora2007** [comment]
It should be. Could you make sure you've updated and have done a hard refresh on your device? 

Re-reading your issue, the first popup is not an error, but just saying that the previous page you were on when it loaded is no longer accessible, because your login expired, and hence it redirected you. Second just shows that the login is not correct. 

The original issue that was fixed was old safari browsers couldn't load the app and didn't render well.

**Comment by HerrFrutti** [comment]
after clearing all browser data, it seems to work. Thanks!
