### ISSUE TITLE
Epic: API Sources

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#148]
Sources for where we can pull data from:
# Manga
https://comicvine.gamespot.com/api/ http://api.comicvine.com (Manga/Comics)
MangaDex 
https://myanimelist.net/apiconfig/references/api/v2#operation/forum_topics_get
https://jikan.moe/
https://github.com/AniList/ApiV2-GraphQL-Docs
https://bato.to

# Comics
https://www.comics.org/ (https://comiccover.org/api/default.php)
https://inducks.org/
https://docs.google.com/spreadsheets/d/1hhqqedn4mdj1pBtuPRRah-NbZAGKUwwzxCgcKjZnuAg/edit#gid=0
https://metron.cloud/

# Books
https://www.oclc.org/developer/develop/web-services/worldcat-search-api.en.html
https://www.goodreads.com/api
https://github.com/yoavaviram/python-amazon-simple-product-api

**Comment by AniUrbz** [comment]
Hi I like to add the **anilist** api for manga to the proposal if it's no bother.

https://github.com/AniList/ApiV2-GraphQL-Docs

**Comment by majora2007** [comment]
Thanks, appreciate the extra source.

**Comment by majora2007** [comment]
webnovel.com for Light Novels (no API)

**Comment by varoOP** [comment]
Fakku for hentai manga. (https://www.fakku.net/)

**Comment by tanpro260196** [comment]
Irodori Comics too, they overlap with Fakku alot but there is some title only they have: https://irodoricomics.com/

**Comment by Gin-no-kami** [comment]
mangaupdates.com for Manga & Light Novels (no API)

**Comment by GlassedSilver** [comment]
doujinshi.org for the media type doujinshi. (I would specifically like to HEAVILY suggest we implement a media type of doujinshi btw. It has overlap with manga, but being FAN-made manga releases of existing series it would be helpful to have it exist next to, but not within the same library (and metadata-fetching) type)

(bonus if the "parody of" field (unless it's original, because yes, non-"parodizing" doujinshis exist as well) links to the series of the manga library (and vice versa, as in: "show _n_ doujinshi for this series" in the Doujinshi library)

**Comment by majora2007** [comment]
Hi @GlassedSilver, can you please provide your thoughts via a comment on this story for relationships? I feel like you may have some insights into additional relationships between series for doujinshis. 

https://github.com/Kareadita/Kavita/issues/1182

**Comment by GlassedSilver** [comment]
> Hi @GlassedSilver, can you please provide your thoughts via a comment on this story for relationships? I feel like you may have some insights into additional relationships between series for doujinshis.
> 
> #1182

I'll check that out, skimming your introductory post over there already got me giggly.

I am absolutely ecstatic that someone values the relationships and tying a franchise together in an easy to pick up from start to finish way as I do!

Re-discovery of my own library, but also being able to present it meaningfully and with in-depth information to others is very important to me. You don't randomly align books on your own bookshelf as well, just because you can tell where which book is by remembering the color of the side of it and whether it had big or small letters for the title. :)

I'll be happy to give feedback for that. I also - just today - checked Kavita's roadmap (that's why I'm in this thread :D) and got very excited to see that metadata scraping is planned for a fairly soonish (if not released, then tackled) release! Much appreciated, because the metadata scraping world for manga is... dire. :D

To get GOOD and thorough metadata in my library, even if it needs to be manually managed in some bits, is of high importance to me. And also for that metadata to be writable to a sidecar file, so I only need to take care of scraping/editing ONCE and if I ever had to change (or ADD!) software in my stack I could lean on my previous work! :)

**Comment by Itadiki** [comment]
For Bande dessinée (french comics) the reference is https://www.bedetheque.com/

**Comment by majora2007** [comment]
@Maltavius please keep this thread on topic for external api sources and not requests. ComicInfo is already supported. Thanks.

**Comment by shimizurei** [comment]
MangaUpdates has an API now! https://api.mangaupdates.com/

**Comment by majora2007** [comment]
Thank you everyone for the feedback. I have decided to go a different direction to provide external metadata into Kavita and hence will unpin this issue.

**Comment by byzboo** [comment]
and what is that direction ?

**Comment by majora2007** [comment]
This is no longer something I'll be pursuing in base Kavita. I'll close out this issue. Thanks to everyone who contributed a source.
