### ISSUE TITLE
Organizing large amounts of PDF's not working

### ISSUE THREAD

**Issue by ImDevinC** [Kareadita/Kavita#1514]
**Describe the bug**
I have a large amount of D&D PDF's in the following format:
```
- Books\
  - D&D5e\
    - Monsters & Races\
      - D&D5e - 5e Creatures.pdf
      - D&D5e - Automatons.pdf
      - D&D5e - *.pdf
    - Player Companions\
      - D&D5e - Alchemist.pdf
      - D&D5e - Backgrounds.pdf
      - D&D5e - *.pdf
    - **\
      -  D&D5e - *.pdf
```
When I add the "D&D5e" folder as a new library, the PDF's are scanned properly, but they don't show up according to folder organization like I'd expect. IE: I would expect a new series for each folder. However I get mixed series' with some of the different PDF's in them that look to be based on the `D&D5e` title in the file.

**Expected behavior**
I would expect a single series per folder. IE: Monsters & Races, Player Companions, etc

**Screenshots**
![screenshot_2022-09-05-23-59-41](https://user-images.githubusercontent.com/3997333/188567568-20e380eb-bf73-412b-8eec-6b9fa9cda5a4.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chrome 104.0.5112.79 
 - Version 0.5.6.0

**Comment by therobbiedavis** [comment]
Kavita itself doesn't really use folder names for parsing, only filenames. This looks to be working as expected. https://wiki.kavitareader.com/en/guides/managing-your-files/pdf

As of v0.5.6 we changed to requiring files to be within folders for scanning improvements and optimizations, not for any parsing changes.

**Comment by ImDevinC** [comment]
Thanks, sounds like Kavita won't work for my situation. Appreciate the fast response

**Comment by therobbiedavis** [comment]
@ImDevinC We have would like your feedback on better supporting PDFs. https://github.com/Kareadita/Kavita/issues/2578

**Comment by ImDevinC** [comment]
I appreciate you reaching out, but when Kavita didn't fit my solution, I moved on. I glanced at the feedback proposal and it seems decent, although more aimed specifically at magazines and not necessarily a defined tree structure for organizing books.

**Comment by huntsfromshadow** [comment]
I'll respond as I have the same issue as @ImDevinC 

So with PDF game books we end up having a folder-based structure.
My library for instance is categorized by publisher, system, and type.
```
- RPGs \
-- WOTC \
--- ADnD \
---- Core \
----- Player Handbook.pdf
----- DM Guide.pdf
---- Darksun \
----- Darksun Adv 1.pdf
----- Darksun Box Set \
------ Box Set Book.pdf
------ Box Set Maps.pdf
```
Now that may be a bit overkill.  One likely could get away with things on a more flat level but the big issue is some books (a lot in fact) are multiple files.  Eg This book may have maps with it, character sheets, and books.  If those files are 'clumped' together in a single logical entity tags could be used to sort through other criteria. 

However, I'd say most people would still categorize books into publisher and system folders.  Due to name collisions which do happen between games, publishers, systems, etc.  Or in the case of the user above they sort it by content type for quick access.
