### ISSUE TITLE
Allow configurable locations for `wwwroot` and `config`

### ISSUE THREAD

**Issue by dit7ya** [Kareadita/Kavita#1515]
**Describe the bug**

I am trying to package Kavita for NixOS (https://github.com/NixOS/nixpkgs/). It would be really nicer if the resulting binary (`API`) can be called with arguments for `wwwroot` and `config` folders since currently they need to be present on the path where the binary is being called from. This makes packaging the app harder and complicated.

Please let me know if anything is unclear or if there is a simpler existing solution.

Edit: I think this should also include any other data directory or as such.

**Comment by majora2007** [comment]
Hi, can you help me understand why they need to be in different locations, esp the wwwroot?

**Comment by dit7ya** [comment]
The binary tries to find the webroot directory relative to where it has been called from. So I am getting errors like  
    System.IO.FileNotFoundException: Could not find file '$PWD/wwwroot/index.html'.

**Comment by majora2007** [comment]
If you're moving the executable, couldn't you setup a soft link for the directory to point to the location so the program is none the wiser?

**Comment by pkreuzt** [comment]
May I suggest using running program user's home as default place for config dir? This would allow some degree of configurability and ease updating process. For example, in a linux install you can create a system user with home at /etc/kavita or /var/lib/kavita (or whatever) and the binary would search there for config. When updating it would be then easier to just copy over install directory without danger to existing config.

A switch to specify config dir would be a great extra, though.

**Comment by majora2007** [comment]
I have no plans to offer a configuration to change the config, but I can confirm soft or hard links work completely fine. Multiple users are doing that themselves. 

I plan to keep Kavita managed within the folder it ships in. I plan to build auto-updating in the future.

**Comment by Misterio77** [comment]
FYI @majora2007: The idea is to make it possible to separate software artifacts (code, build outputs, scripts, etc) from state on deployments. On Kavita `config` is state (thus should be kept in a mutable, persisted location), while `wwwroot` is an artifact (thus should be part of a "package", possibly somewhere else).

NixOS (and probably other similar platforms) tackle this by putting the software artifacts in an immutable location (in our case, the Nix Store), that's why we'd like to have `wwwroot` be configurable. A symbolic link is possible, of course, but the idea here is to make automated deployments where everything "just works". 

Making these sort of things configurable is helpful to make the software behave better on different platforms that work under different principles. Jellyfin, for example, [does this](https://jellyfin.org/docs/general/administration/configuration); it's not an arbitrary design decision.

An interesting article on the subject: https://drewdevault.com/2021/09/27/Let-distros-do-their-job.html

---

Hope that helps understand the usecase a little better. I can implement this and contribute the patch, if you'd be interested in the feature.
CC @natsukium @dit7ya
