### ISSUE TITLE
Putting books in a folder may or may not group them in the same series in Kavita?

### ISSUE THREAD

**Issue by leocordis27** [Kareadita/Kavita#1517]
Putting books in a may or may not group them in the same series in Kavita?

**Expected behavior**
Putting ebook file in a specific folder will put them under the same series.

**Screenshots**
I created a new folder "Cactus & Succulents" in the root ebook folder
![image](https://user-images.githubusercontent.com/111774381/189051507-70f4da3c-649b-44d2-b7db-903fbb103c89.png)

There are 6 books inside the "Cactus & Succulents" folder
![image](https://user-images.githubusercontent.com/111774381/189051659-fcac92ed-79cb-4da0-b69f-b7e0aab6ddfc.png)

Kavita made 1 series "Cactus & Succulents" and 3 individual series (books?)
![image](https://user-images.githubusercontent.com/111774381/189051999-101e38b7-2023-4112-89f2-47eba211da41.png)

There are 3 books inside the "Cactus & Succulents" series
![image](https://user-images.githubusercontent.com/111774381/189052207-1df68e97-4906-4170-a3b6-1a51738f98eb.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Brave
 - Version 1.43.89

**Additional context**
I did not touch any metadata or rename any of the ebook file.

**Comment by ThePromidius** [comment]
Two things here:

- Different file formats can't be mixed. (Use reading list to group them)
- The rest of the pdfs not grouping is because the filenames differ too much. The filename parser can't really find what series it's from so it creates a new series.

**Comment by leocordis27** [comment]
> Two things here:
> 
> - Different file formats can't be mixed. (Use reading list to group them)
> - The rest of the pdfs not grouping is because the filenames differ too much. The filename parser can't really find what series it's from so it creates a new series.
> Also, Kavita itself doesn't really use folder names for parsing, only filenames.

Let me play around with the file name for other case

**Comment by majora2007** [comment]
Hi @VegethB, I understand you want an encapsulation of one series with a set of different files and not them being split up into different series for each format.

Have you tried Ubooquity? I believe it works the way you want it to. Kavita is not a good solution for you based on your comment. 

You need to understand difficulty vs vision. My vision for Kavita is not to have all formats to group into the same series as it doesn't make sense to me or for my needs. 

Best of luck in your search to find the software that meets your needs. If you can't, you should build your own. That's why Kavita exists, nothing met my needs.

**Comment by ThePromidius** [comment]
Because they're different format they need different readers and due to pdfs not having proper metadata, the parsing is done differently.

What i think its the main limitation is pdfs parsing is extremely limited.

And you'd probably say... Then use folder structure for grouping...
The answer is no.
The reason is how Kavita was build initially. Changing it now would require a whole rewrite of kavita which likely won't happen.

Hope this answers some of your questions.

**Comment by majora2007** [comment]
> So: if you have a series of cookbooks... for example a series called "The Secrets of Eggs" (randomly invented name).
12-volume series;
The first 8 in .epub and the last four released on the author's website in pdf (because for X reasons the last 4 have not been officially released by the publisher).

This is an edge case that you are wanting designed around. Think about this more common situation; I have KonoSuba which are archives acting as the Manga and I have KonoSuba which are eub, which represent the Light Novel. I would want these separated. 

Your edge case is valid, however, I do not have a solution for you nor can I offer a solution without changing the core of how Kavita functions. In addition, think about features of Kavita, where Kavita estimates time to read a series. When mixing different media together, the code has to handle all those different logic and the code becomes needlessly complex.

Ubooquity is the only one that maps the folder because it's very limited what you can move onto. In order to drive these further enhancements, like the other software you quote, you need to set up certain rules. 

I would suggest perhaps using Calibre/Calibre-web for your book library or using Calibre to convert your epubs->pdf or vice versa or re-acquire when you run into these situations.

**Comment by ThePromidius** [comment]
> It means that they have already been processed by the server and ended up where they should be (therefore pdf series1 and ebook series1) but then hides them and displays them inside the collection.

This is actually interesting and there's a feature request for it. I'd like to have this as well.
Ideally, in library view, it'd show the collection card and hide the individual series card.

Related:
https://feats.kavitareader.com/posts/163/library-collection-view-options

**Comment by majora2007** [comment]
I'm going to close this issue. It's become divergent of the original opener's request. @leocordis27 feel free to open another thread if you still need support.

@VegethB It is very clear Kavita isn't the solution for you, best of luck on your search for a software that meets your needs.
