### ISSUE TITLE
PDF Reader Feedback

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#1523]
With the new PDF reader having been out for a few releases, it's not time for the community to come and provide feedback for what they like, what they want, what they don't want/need. 

For example:
Tap to paginate is a required feature for many users. 

Help me understand how you are using the PDF reader, what type of content are you consuming, does the new reader enhance your experience from the old one (which was just an image render of each page), etc.

I will take this feedback and update the PDF reader and provide customization hooks.

**Comment by hisdivineorder** [comment]
PDF Reader: Option to Swap Default Scroll Direction/Type for All Media/Per Library - I imagine an option to change the default scrolling option for the PDF Reader from up/down to side to side or any of the other options. This option could be set as default across all PDF's per library and/or per user.

PDF Reader: Tab Pagination (Tapping Left/Right Edge to Progress PDF) -  I also suggest tab pagination for PDF files be an option for right/left edges for horizontal use cases.

PDF Reader: Option to Auto-hide the Menu - To go with the earlier suggestions, an option to automatically hide the menu once the earlier changes are in place would give a seamless reading experience similar to epub and cbz.

**Comment by sgpopuri** [comment]
I started using Kavita for few days and loved it. This is definitely better than Calibre. For pdf reading I have a suggestion.
Adobe Acrobat supports dark mode where there content can be viewed in dark. Kavita has dark mode however only the panel gets dark.
This is how it looks in Kavita:
![image](https://user-images.githubusercontent.com/2023128/190902426-a21b76de-64bf-4204-a81e-dd1718ff352a.png)
This is what I am requesting for:
![image](https://user-images.githubusercontent.com/2023128/190902447-55be8e6c-6ee7-4fe4-a35a-772851719efe.png)
Thanks

**Comment by Eric111111** [comment]
Hello,
Would like to say I am loving this program. Having one issue - not all my pdf files are loading. No idea what's going on. Any help would be appreciated. Thanks :)

**Comment by majora2007** [comment]
@Eric111111 Please join discord for support or create a github issue and I will get to you. Please leave this thread for feedback only.

**Comment by Brancliff** [comment]
It doesn't seem the PDF reader supports multiple chapters? I've got over 100 entries of a magazine, and the library recognizes that they all belong together (the "print length" is over 10,000 pages). However, I can only read the first 100-or-so pages in the first edition of the magazine, and there doesn't seem to be any way to jump to another one.

**Comment by lukaszliniewicz** [comment]
I think this implementation is very good, both in terms of stability and functions. Yes, tapping would be nice, but it is now perfectly usable. Great job! What I miss (though it doesn't apply to the pdf reader only) is the ability to copy and save text fragments as notes and perhaps being able to organise them (tag and/or put in a folder) with links to the source material. Do you think there is a chance something like that will be implemented at some point?

**Comment by fx999dev** [comment]
It would be nice if the fullscreen mode would support font-size-scaling. At the moment the fullscreen mode is not very helpful on e-ink readers like boox because the font size is too small.

**Comment by franperiali** [comment]
The bookmark function would also be interesting for pdf reader

**Comment by hollisticated-horse** [comment]
- the **light/dark theme** does not follow user preferences (if there are any parameters for that in the user setting ? )
- the **document outline** does not have enough contrast in dark mode (text is hard to see in grey)
- the **thumbnail view** does not have enough contrast in light mode (barely see which page is selected) 
- slight shifting of icons when cursor hover, seen also in ebook reader.
- also overlap of buttons on some icons
- slightly bigger and more spaced out ui elements
- the **findbar** could maybe use a box shadow effect, for better contrast, and maybe a bit bigger
- something with the scrolling (I'll come back to that in a minute)

---
- Could be a good idea to work on highlighting, both in pdfs and ebooks, with a similar UX/UI flow ?  
- have a progress bar showing roughly the position in book ? 

---
- **consistent icons** across both in ereader, pdf reader and manga/comic book reader ? 
- maybe add the kavita green for toggled or selected elements

If need be, I can edit, update or remove the post from this issue to move it somewhere else.

**Comment by majora2007** [comment]
@hollisticated-horse this is actually to gain insight in which modes of the reader people use. The user preferences were never hooked up because I wanted to gather feedback from users if the pdf reader was a value add or if they preferred the old image based one. 

Since you have a nice write up, would you please also drop which reading modes you use? Like are you using the scroll mode horizontally? Are you using the thumbnail view (on left) to quickly preview? 

The pdf reader library I chose is very versatile, but that doesn't mean Kavita as a reading system needs all those features for the user.

**Comment by hollisticated-horse** [comment]
I don't have a lot of pdf documents on my Kavita instance. 

I mostly navigate with  text selection active.  I use it to copy snippets of text for referencing. I would probably use highlighting and bookmarking when implemented. 

For the side bar, the thumbnail view clearly helps me navigate more quickly through the document, in search of something particular. If the document is colourfull or has varying layouts, i'd go for thumbnail. 

The document outline on the other hand helps me quickly have an overview the document and target specific sections. Especially if it's a text document, it is far easier to navigate with the outline. 
- having the outline show where the user is in the book is probably a must have. 

For scrolling, it really depends on the plateform used. I barelly use my phone and don't have a tablet. I mostly read through my browser. 
- mostly **horizontal scrolling**, with **page-fit**, since I have a large enough screen to read in that manner. But from experience, I'd probably zoom in if the text is to small to read, and use the vertical scroll, or wrapped-scrolling. Usefull for text-only basic document layouts.

In the case of wrapped scrolling, odd/even spread makes sense, though I haven't used it yet. 

I'm mostly either scrolling or using keyboard, i don't use arrows from the UI. 

I haven't had to use the search bar yet either, but it also seems clearly essential, and it seems to work quite well !

**Comment by Gin-no-kami** [comment]
I primarily read PDF files that have been created from a manga with some OCR information overlaid on top (Mokuro2Pdf). This allows me to use a lookup tool (yomichan) when reading when I encounter a word that I don't know. The features that are missing for this to work using the Kavita PDF reader are:

1) Right to left reading mode, just like the manga/comic viewer. This would allow for spreads to be reversed, thus allowing dual page spreads to be rendered properly. 

2)  Tab Pagination to respect the right to left reading mode.

**Comment by iroQuai** [comment]
I really love Kavita for it speed and ease of use. At this moment, I'm using Kavita for comics, calibre-web for Fiction, mostly epubs (i tried using Kavita for it, but series organisation is a mess) and Bookfusion for non-fiction (pdfs and epub). 

 Why Bookfusion? Because of all the tools I've tried, bookfusion has by far the best integration of highlights and notes (which I use a lot for non-fiction ). I got a year free subscription to try it out. Although I do like it, I doubt I'll pay at the end of this year. I'm really all for selfhosting. I don't like being dependents on a third party.

So when you ask for PDF reader feedback, by far the most important feature request i have would be noted and highlights. I do realize that this probably is out of the scope of the original purpose (manga/comic reader), but when Kavita would handle epub and pdf both well too, this could definitely be an all-in-one solution!

**Comment by rodhfr** [comment]
I don't know the possibility of this is, but the only thing preventing me from switching my workflow entirely to kavita is that the pdf reader doesn't have "anti-aliasing". The characters look very sharp to me. I'm still stuck on the ms edge pdf reader, which is really bad because there's no way to sync across various devices. My use case is mainly to read printed and digital books.

![Screenshot_1](https://user-images.githubusercontent.com/83579016/235318002-9cf7bfcc-89c2-4073-bcd7-87a245a99a5e.png)

**Comment by N1N74** [comment]
Internet archive's book reader is very fun to use and I highly recommend a similar UI for side-by-side mode. The turn page animation and side-by-side pages with the selectable bits on each side (part with hover-text on the right in the image, it feels like flipping to a page number on the book) are extremely satisfying to use. Also the horizontal progress bar.

<img width="960" alt="image" src="https://github.com/Kareadita/Kavita/assets/39383296/bcbe2452-9880-463a-bdd8-804896699c4b">

 

A demo of the same is given [here](https://archive.org/details/birdbookillustra00reedrich/page/136/mode/2up?q=plover) and the source code for BookReader is [here](https://github.com/internetarchive/bookreader) if it's of any use. The left-side search results is also very useful. I have been desperately trying to search for such a UI in any book reader since I find it to be that good. It even has TTS. Also, it seems like I'm not able to select text from a document in the Kavita demo. It would be extremely cool if BookReader were integrated into Kavita as a separate option too.

**Comment by webysther** [comment]
This book reader support load pdf in stream, which is great

**Comment by eliluong** [comment]
Does the new PDF reader load the entire PDF before rendering it in the browser? I can't tell from the demo website, and I am still on an older version. I sort of like the old one, as I have some large 100+MB PDFs that would take a long time to load remotely (slow upload speed), and I feel getting a few images rendered is faster.

**Comment by xrishox** [comment]
i use this with mokuro2pdf content and pdf.js works great with it.  almost all pdf readers break with vertical japanese text. Calibre, ibooks to name a few examples. it's almost by a cosmic miraculous accident that pdf.js happens to work with vertical text. i really hope if this gets replaced with something else that we make sure that it doesn't break mokuro2pdf support.

<img width="1234" alt="Screenshot%202023-07-20%20at%206 54 23%20PM" src="https://github.com/Kareadita/Kavita/assets/23132250/72e887b3-8f81-48b0-bd17-d8dbf8b55c0d">
this is text highlighting being broken by apple ibooks. instead of going down it goes across.

![Screenshot 2023-07-20 185817](https://github.com/Kareadita/Kavita/assets/23132250/dc096ba8-d70d-4236-a098-dde5aa1b1c90)

being able to highlight text is necessary for dictionary tools like yomichan

this is text highlighting being done properly by kavita.

**Comment by vcntt** [comment]
I would like to use Kavita to read scientific papers. Would be handy if I could add highlights / comments.

**Comment by bishopj15** [comment]
It would be great if the PDF reader had the ability to rotate pages

**Comment by TheoQc** [comment]
When going into fullscreen mode, the even-spreads/odd-spreads setting gets lost and we are back to no-spreads. It would be great if the setting would carry on into fullscreen.

Another nice to have feature would be to do it page per page, waiting for the whole pdf at once can be long before seeing something.

**Comment by thegreatestgiant** [comment]
I would lover to be able to save preferences like I can with ebooks
For example I want it to always render in dark mode the page-width mode to be page-actual

**Comment by djdole** [comment]
It would be useful for users, when a book has multiple different available file format types, for Kavita to provide a setting giving the ability to choose and set the prefered book format type (perhaps even by library, and/or by user).

Example,
Library (Technology Books):
Book Record: O'Reilly - Head First C#
Files:  
- O'Reilly - Head First C#.epub
- O'Reilly - Head First C#.pdf

Library (Comics):
Book Record: Kodansha Comics - Parasyte Vol. 1
Files: 
- Kodansha Comics - Parasyte Vol. 1.cbz
- Kodansha Comics - Parasyte Vol. 1.pdf

Library (Poetry):
Book Record: Edgar Allen Poe - The Raven
Files: 
- Edgar Allen Poe - The Raven.epub
- Edgar Allen Poe - The Raven.mobi
- Edgar Allen Poe - The Raven.pdf
- Edgar Allen Poe - The Raven.txt 

User A: Prefers Kavita to open / download PDF files for all libraries they have access to.
User A: Comic Library: (still)Prefers Kavita to open / download PDF files, for the comic formats.
User B: Technology Library: Prefers Kavita to open / download PDF files, for combination of text & images.
User B: Comic Library: Prefers Kavita to open / download CBZ files, for the comic formats.
User B: Poetry Library: Prefers Kavita to open / download EPUB files for mainly text.

**Comment by vijay-prema** [comment]
As others also mentioned, I would really like pdf page to truly render in dark mode (basically invert the CSS so page is black and text is white).  Currently Kavita dark mode just makes the web background dark, not the pdf page.

I would like to add that can achieve dark pdf page in Kavita by installing this Firefox extension https://github.com/Max-Github/FireFoxInvertColors and press Alt+R to invert white page into dark page.  But it only works on desktop, not on mobile.

**Comment by obuno** [comment]
> 
>     * the **light/dark theme** does not follow user preferences (if there are any parameters for that in the user setting ? )

I'd follow on that one, always clicking on the "dark mode" within the PDF reader while my user preset state "dark"  within kavita. Perhaps there is a hard setting one could manually toggle on the vm/container ?

Thanks !

**Comment by NeilJared** [comment]
My pdf library is divided into 4 main groups: magazines, comics, books and papers.
It is enough for all except for books, where I find it more usable in the way it has index, chapters and sections, so I use it a lot when I open a book, on the left hand toolbar. 
I love you added again the possibility to select odd and even spreads, since many visual books need double page view. Thanks for including that again. 
I would love to use sweep page navigation, simulating a paper book.
I would find really useful to recover name editing, since latest version does not allow to edit name. Another option I used to add on Endnote, Zotero, Reference Manager and so, is the possibility to download and add to Kavita the reference info for each file. On books I think is easier as Calibre does, it gathers info crawling somewhere on the net and adds basic info as meta data, since it cannot be included on a pdf file. 
Cheers

**Comment by jlar0che** [comment]
It would be amazing if we could highlight and comment on text.

**Comment by jp-man25** [comment]
> I primarily read PDF files that have been created from a manga with some OCR information overlaid on top (Mokuro2Pdf). This allows me to use a lookup tool (yomichan) when reading when I encounter a word that I don't know. The features that are missing for this to work using the Kavita PDF reader are:
> 
>     1. Right to left reading mode, just like the manga/comic viewer. This would allow for spreads to be reversed, thus allowing dual page spreads to be rendered properly.
> 
>     2. Tab Pagination to respect the right to left reading mode.

Any updates on this? It's pretty important for reading Manga, so many beautiful double spreads...

**Comment by NeilJared** [comment]
> I love you added again the possibility to select odd and even spreads, since many visual books need double page view. Thanks for including that again.
> I would love to use sweep page navigation, simulating a paper book.

Thanks for making this options available again. I think is a great value added

**Comment by majora2007** [comment]
I have released some small updates to the PDF reader in v0.8. There is a lot of valuable ideas in here, but this format is not ideal. 

For anyone that has an idea they are dying for, please use Discussions to open a feature request so more from the community can upvote and help prioritize the feature. 

Thanks to everyone that has submitted ideas.
