### ISSUE TITLE
Kavita Sometimes Serves Wrong Page to User

### ISSUE THREAD

**Issue by Rvby1** [Kareadita/Kavita#1537]
**Describe the bug**
When reading a manga volume, Kavita will randomly serve a page from much later in the volume (seemingly at a consistent offset of 34). This page offset makes the correct page impossible to find, and this "replacement" persists across browser and Kavita resets. For example, when reading page 103, I would consistently get page 137 instead. Page 104 would display correctly.

Reinstalling Kavita and refreshing the metadata did not resolve the issue. Deleting the library did, but this does break progression tracking for the library.

**To Reproduce**
1. Replace .db file with the provided .db file 
2. Place the provided file in F:\Manga\My Hero Academia Manga (Digital)\file.cbz
3. Go to page 104 of the manga
4. See that wrong page is served... hopefully.

**Expected behavior**
Kavita should serve the correct page, not an offset page.

**Desktop:**
 - OS (Kavita): Windows 10 Pro, Version 10.0.019043
 - OS (User): Windows 10, 10.0.19043
 - Browser: Firefox, 104.0.2
 - Kavita Version: v0.5.6

**Additional context**
I recently updated from a version that was about a year old. It may be that some issue occurred with migrating/upgrading the database between that version and the most recent version.

**Comment by majora2007** [comment]
This issue is likely due to jumping from such an older version to a newer one paired with the fact that recently I have removed migrations (which keep Kavita in working state while retaining user data) from releases that were old enough. 1 year is over the old enough marker for me, hence why this is likely the issue present here. 

During that one year, Kavita is almost a completely new system and a lot of the expectations where files go has changed quite a bit. 

To anyone that is on older versions, please a) Try to just keep up to date and b) update 2 version numbers a time to get up to the latest.
