### ISSUE TITLE
2-page-layout not working

### ISSUE THREAD

**Issue by handy1928** [Kareadita/Kavita#1605]
**Describe the bug**
In every manga i tried (i tested a lot) always before a double-spread (that is one image) the 2 pages (2 images) before the double-spread, only 1 (the 2nd one) is visible. I did a fresh docker install and also tried many browsers (which i never used for Kavita) with the 0.6 update.

**To Reproduce**
Have a file where the double-spreads are merged to 1 file and load it to Kavita in double page mode.

**Expected behavior**
Before the double-spread both pages should be there in correct order like the pages before the 2.

**Screenshots**
The video shows the issue, a page is missing before the double-spread.
[video](https://discord.com/channels/821879810934439936/976086722263797840/1033474941112291420)
The image is the missing page from the video.
<img width="1920" alt="missing page before double page" src="https://user-images.githubusercontent.com/43494747/197360728-23bfeeaf-fd0b-4f92-801b-ca7b292ccb6f.png">

That are my profile image reader settings
<img width="1705" alt="profile image reader settings" src="https://user-images.githubusercontent.com/43494747/197360784-4e53d37f-3cdf-48bb-b0e1-6362943c6d42.png">

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox, Chrome, Edge on Windows
 - Kavita Version 0.6

**Comment by majora2007** [comment]
This is not an issue. How do you expect Kavita to display your single image with a spread? 

There is going to be some basic rules we have to follow so that we lay it out best for the user rather than enforcing 2 pages per screen. So if the one of the pages is a spread (2 pages spread represented as a single image), then the pages before and after that spread will always be singles. 

Do you have any other issues you're facing?

**Comment by majora2007** [comment]
Talked with user and understand that this issue is that images are not being rendered. 

Testing material:
[Test_even_spread_2.zip](https://github.com/Kareadita/Kavita/files/9910710/Test_even_spread_2.zip)
[Test_odd_spread_1.zip](https://github.com/Kareadita/Kavita/files/9910711/Test_odd_spread_1.zip)
[Test_odd_spread_2.zip](https://github.com/Kareadita/Kavita/files/9910712/Test_odd_spread_2.zip)
[Test_even_spread_1.zip](https://github.com/Kareadita/Kavita/files/9910714/Test_even_spread_1.zip)

**Comment by ocgineer** [comment]
A spread always starts on an even page, if it isn't then the cbz has an incorrect amount of pages.
Going from that--for manga--any single pages, you render even pages on the right side and odd pages on the left side, so there is no need to show a single page before and after a spread.

The only tricky issue is the cover, but nearly all have the blank page that is the backside of the cover removed, so page 1 is the first page, where page 0 the even one is the cover and it works out. So you could "show page 01 - cover" as dual page, or have the cover and page 1 be single before starting dual-view following the odd-even rule.

**Comment by majora2007** [comment]
As discussed in discord, this is working now. Thanks for the help in testing.
