### ISSUE TITLE
Various authors in the same series (Only with Calibre)

### ISSUE THREAD

**Issue by Rougecarlos** [Kareadita/Kavita#1612]
Kavita's version is 0.6 and Calibre is 6.7.1.

The problem is when you have a library of Epubs in Calibre and a series has more than 1 author, when doing the scan Kavita goes crazy and only shows you 1 Author, the others disappear although when you scan you can see the covers for a few seconds charging, but then the books do not appear anywhere or in the search engine

To reproduce it, it is easy to create a library in Calibre, add two or more books, both from the same series with a different author.
For example:

(Title) Harry Potter and the Philosopher's Stone - (Series) [Harry Potter [1]] - (Author) J. K. Rowling
(Title) Harry Potter and the Chamber of Secrets - (Series) [Harry Potter [2]] - (Author) Z. K. Rowling

With that in Kavita when searching the Calibre library you will only find 1 the other will disappear.

That if, ONLY happens with the Calibre libraries, if you save the books and scan them without the Calibre format ordered by author, and failing that they are all in a folder with the name of the series, then Kavita does take series well with various authors

Edit: 
There is a somewhat dirty solution ^ ^.

In Calibre Library in the books add the same Co-Author in all, then Kavita if he gets it right:
In the example it would be:

(Title) Harry Potter and the Philosopher's Stone - (Series) [Harry Potter [1]] - (Author) J. K. Rowling
(Title) Harry Potter and the Chamber of Secrets - (Series) [Harry Potter [2]] - (Author) J. K. Rowling & Z. K. Rowling
IMPORTANT, the common author need to be the first

**Comment by Selid** [comment]
I'm using Comicrack myself and I noticed some change with 0.6.0 and the people who made the book : 
I had a manga with the name of the serie set to its japanese name, in a folder with this name, the author was referenced in both writer and penciller. I decided to go with the internationnal name, made the change to the comicinfo.xml and move the files into a folder with that name. Now both writer and penciller are gone.

I have another serie of one book with multiple writers, pencillers... none are shown in Kavita. But for another one they are detected (both have been modified with comicrack and added to kavita today).

I'm not certain my issue and yours are connected, but they seems pretty close and it could give some info as to where the issue is in the code. I move it to a separate issue if needed.

**Comment by majora2007** [comment]
Kavita reads metadata from within the epub files and Calibre does not write to the file by default. It has it's own database and only maps if you polish or save to disk (opf inside the epub). So this isn't a bug.

**Comment by Rougecarlos** [comment]
The ebooks have the metadata saved, as i said, only happens with calibre library, I think is because the format of save files in calibre, the ebooks is saved in folders ordered by Author, and kavita gos crazy if in the metadatada in the same series have books in diferents folder, in the case of Calibre, diferents Authors, in this zip i copy a test calibre library set as the example, al metadata, are embed.
 If you make a new Library in Kavita and Scan only detect you 2 Books (Or 3 if is the last one), and the others are missing, but if you rescan the library the cover shows for a few seconds, and maybe Kavita take another Autor and Show other diferents books. Test it if you can.

https://mega.nz/file/gHNzgJaI#1ImOf4YlOBHgPVQe4cSpzdKNN07KY6T5WPc0DWdPcuM

**Comment by majora2007** [comment]
I downloaded your example, I need to understand, where is your Library root? 

Is it like /Test/ as library root and your different author folders underneath? 

or is it like /Books/ as library root and /Books/Test/J. K. Rowling?

**Comment by Rougecarlos** [comment]
It is the /Test, if you look you will see that the Caliber metadata files are there, it is the main one of the caliber library that orders the books by the name of the Author, in that Example there are only 3 authors that I have put, but let's go there would be all you have in caliber.

As I say, the problem may come because it does not identify books from the same series that are not in the same folder. And since they are different authors, Caliber puts them in other folders even if they belong to the same series.

The only bad thing is that it only recognizes one author (folder) per series, if there is another book of that series in another folder it disappears.

A test that you can do is to take any series of ebooks, which has the metadata embedded, and take a book from that series and put it in a different folder, when doing that it will only go one of the two routes and when scanning it will randomly take one or other

**Comment by majora2007** [comment]
Okay, yes you cannot have multiple series parallel to the library root. So if you had this layout but your root was one level above, you would be completely fine. 

But since you have multiple series next to each other right under the root, they are conflicting with each other. 

So this is not an issue with Kavita, you just need to add another layer before your author folders and Kavita will work as expected. 

So:
/root/Test/Author 1/Series 1 files
/root/Test/Author 2/Series 1 files
/root/Test/Author 3/Series 2 files

**Comment by Rougecarlos** [comment]
Ok thanks, luckily I only have a few series with multiple authors so it's not much to modify.
Thanks for answering, incredible work you do with the program.

**Comment by majora2007** [comment]
Just adding for anyone that searches, you can use Readarr and have it link with Calibre to properly tag and enforce the correct structure.

**Comment by JMartJonesy** [comment]
@majora2007 can you elaborate more on this?

**Comment by majora2007** [comment]
> @majora2007 can you elaborate more on this?

Can you be more specific on what you want to know?
