### ISSUE TITLE
Can't navigate backwards through a comic more than a couple of pages

### ISSUE THREAD

**Issue by pssandhu** [Kareadita/Kavita#1619]
**Describe the bug**
I can only navigate backwards in a comic a couple of pages before the reader stops updating the image.

**To Reproduce**
1. Open a comic in single page mode
2. Navigate forwards through the comic e.g. 5-10 pages
3. Try to nagivate backwards to the start
4. Image stops being updated after going backwards a couple of pages

**Expected behavior**
Should be able to navigate forwards and backwards freely and the image should update accordingly.

**Screenshots**
Video of issue on kavita demo server:

https://user-images.githubusercontent.com/11130930/198714603-12fbf002-e814-468d-beb0-bd0cd1bc67c9.mp4

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox, Vivaldi
 - Version: Kavita 0.6.0.0

**Comment by majora2007** [comment]
The following comments are not for you, but for me as I'm debugging his issue. You can unsubscribe, this will go into the next release. 

I'm able to reproduce this only when I load a manga then page forward a few, then heading backwards for some time, the prefetched buffer is correct, but the underlying image (canvasImage) isn't reflected in the HTML, although all onloaded for prefetched images are correct. OnPush vs Default is not the root cause. 

![image](https://user-images.githubusercontent.com/735851/199135717-eaccab4a-e75b-425b-9dde-a3a9e84b21ea.png)

**Comment by majora2007** [comment]
When checking navigating backwards, after 4 new image requests (aka buffer doesn't have our images) this "stuck" issue occurs.

**Comment by majora2007** [comment]
The issue is not with a bug in loading or rendering, it is that when navigating forward at a certain point we move to the front of the buffer, as we keep moving, around index 3 we only have one prev page behind us until we hit a point where there is an image that is prefetched much higher than ourselves. 

This puts us in a place where we have to do an ad-hoc image load (which then triggers some issue with render loop not getting triggered). There may actually be some loading issue here as well, the onload and onerror don't trigger when using the new image flow at all.

**Comment by majora2007** [comment]
Solved. The issue is that OnPush change detection uses references to detect when to update the DOM and I was mutating an object's property directly to set the new image source, to avoid overhead of new Image(). However this wouldn't allow Angular to know to update DOM.
