### ISSUE TITLE
High CPU and RAM usage after updating Library, High usuage persists after shutting down and relaunching Kavita 

### ISSUE THREAD

**Issue by Irvanya** [Kareadita/Kavita#1623]
**Describe the bug**
CPU usage is pegged at 100% and RAM usage has increased from the usual ~200 MB to 2GB at startup and increasing over time.  Usage is around 2.7 GB after 45 minutes. 

**To Reproduce**
Unknown root cause.  Server was running normally for slightly less than a week, problem occurred after adding multiple files and renaming them so that the parser would organize them into the desired series.

**Expected behavior**
Kavita memory and CPU usage should remain low, potentially increasing slowly until Garbage collection cleans up stale data.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1 Build 19043.2130
 - Browser: Chrome 107.0.5304.87, problem is server side though.
 - Version:  0.6.0.0 native windows server

**Additional context**
Problem was noticed when Kavita became less responsive.  Kavita remains accessible and other servers running on the same computer continue to run, but with degraded performance.  Files are stored on a local NAS with folders mapped to drive letters on the server computer.

[kavita20221024.log](https://github.com/Kareadita/Kavita/files/9897146/kavita20221024.log)
[kavita20221028.log](https://github.com/Kareadita/Kavita/files/9897147/kavita20221028.log)
[kavita20221029.log](https://github.com/Kareadita/Kavita/files/9897148/kavita20221029.log)
[kavita20221030.log](https://github.com/Kareadita/Kavita/files/9897149/kavita20221030.log)

**Comment by Irvanya** [comment]
After waiting overnight, the CPU usage has dropped back to approximately 0%, but the RAM usage remains at ~2.5 GB.  Server has 24GB of RAM so the higher RAM usage is not concerning.

**Comment by majora2007** [comment]
Okay, first off, I see this spammed in the logs:

> Multiple series map to this folder. Library scan will be used for ScanFolder

This means folder watching is on and a change in a folder occurs, instead of just ingesting that series changes, multiple series exist, so your server needs to do a full blown scan. As full blown scans are more expensive and you're doing a bunch of changes, this might be one issue.

I see another concern:

> The process cannot access the file 'Kavita\config\cache\17336\Jungle Map Pack Banners.psd' because it is being used by another process.

This indicates multiple Kavita instances are open or you are opening files from within Kavita's managed folders. If its not you, then something is amiss.

I see this:

> System.UnauthorizedAccessException: Access to the path '004_001.png[text,burned,title]' is denied.

Which is from opening the reader and trying to send images to the reader. 

So before we jump into the high utilization, I see other issues that are likely to jack up any program.

**Comment by Irvanya** [comment]
I'm going to guess that the full blown scans and rate of change were the root issue, essentially fork bombing my system.  While my Comics directory is updated to fit the new scan requirements my roleplaying game directories and libraries are not all updated to keep the parser happy.

Thanks for your assistance understanding what was causing the problem
