### ISSUE TITLE
Folder watching does not work in Docker for windows container

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#1714]
**Describe the bug**
Folder watching does not trigger when kavita is run in a docker container.

**To Reproduce**
1. Run Kavita in docker container. Have folder watching on.
2. Add new files to a folder within one of the library folders
3. Wait for library scan to trigger.
4. Library scan does not trigger via folder watching.

**Expected behavior**
Library scan should be triggered via folder watching.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker for windows, Docker for linux
 - Browser: Opera GX
 - Version: 0.6.1.19

**Additional context**
I have the log files from when I did some testing tonight. If you want them I can send them over via discord later.

**Comment by majora2007** [comment]
Notes from research, it seems like docker may not be able to support folder watching out of the box and we may have to test with some external program:
https://github.com/merofeev/docker-windows-volume-watcher

**Comment by scare376** [comment]
I figured out my particular issue with folder watching. Folder watching does not work with a network share. My library is shared with my kavita instance over SMB. Spun up a container on the server with the library on it and was able to get folder watching to trigger.

**Comment by scare376** [comment]
So this is now 2 different issues. Windows docker does not seem to support folder watching out of the box and folder watching does not support network shares.

**Comment by majora2007** [comment]
So looking into the network shares, it seems like it might be a configuration option that might be able to enable it:
https://rclone.org/commands/rclone_mount/#vfs-directory-cache
https://forum.rclone.org/t/inotifywait-not-detecting-file-added-to-rclone-mount/28714/2

**Comment by scare376** [comment]
I may try rclone to see if that works but i am not too worried about it knowing now its likely a limitation of using a network share. I tend to update my library whenever i add new stuff to my library. If I do try rclone i'll update here with the results

**Comment by officialdevjackson** [comment]
I am on Windows 11 running Docker and https://github.com/merofeev/docker-windows-volume-watcher gets folder watching working but has side effects like duplicate notifications and notifying Kavita of previously notified files. Overall it still works outside of those bugs, but I would like to see something like this implemented in Kavita itself and without these bugs. I am sure it would be relatively easy, unfortunately, I can't get support from the original dev of the script itself as the project seems to be abandoned as of early 2019. Also, note to other Windows + Docker users, the script only works if you fix a few lines of code.

**Comment by G0lfH0t3l** [comment]
Not sure if this is the correct place and way to post this:

I performed a second install of Kavita in a Docker container because new items in a library are not detected /  added when uploaded to the file system. Only the initial files are scanned / detected after installation. Still no luck with this though.

A manual scan shows the "popup" : Scan queued for .... but no new files/books are added to the library ever.
Library scan is set to Daily.

I am now running Kavita Version 0.6.1.0 in a version 20.10.21 Docker container running on a VM with Ubuntu 22.04.1 LTS.
All files/books are uploaded locally on this machine.

There are no errors in the logs.

**Comment by majora2007** [comment]
@G0lfH0t3l  this is not. Create a new issue for support

**Comment by majora2007** [comment]
I spoke with @therobbiedavis who told me his setup is working. He's on docker with network storage via rclone and only uses folder watching, nightly scans disabled.

@officialdevjackson it's actually not easy to fix in Kavita as Kavita is using native OS hooks. So it should just work.

**Comment by officialdevjackson** [comment]
> @officialdevjackson it's actually not easy to fix in Kavita as Kavita is using native OS hooks. So it should just work.

It works on bare metal Windows but not the Windows version of Docker. If you could give it a shot and tell me if it works for you on Windows Docker that would be great. It could totally be a setup issue or more likely a Docker limitation.

**Comment by majora2007** [comment]
Just going to provide an update here. It seems like Docker on Windows over WSL2 does not support folder watching. All other platforms seems to be working as expected. Users on this configuration can use WSL1 and get it working is my understanding. 

Due to Kavita using native OS hooks, implementing a slower, more compute intensive solution just to support one configuration doesn't make much sense, so I will be officially saying that Docker on Windows via WSL2 is not supported for Folder watching.
