### ISSUE TITLE
Books changed (updated) do not appear in "Recently Updated Series"

### ISSUE THREAD

**Issue by LDShadowLord** [Kareadita/Kavita#1789]
**Describe the bug**
When a book is updated using an external application such as FanFicFare or Sigil, it does not appear in the "Recently Updated Series" tab, despite having been recently updated.

**To Reproduce**
1. Update an Epub file to add a new file to the end of the epub by using an external program such as FanFicFare, Sigil, or other EPUB Editor.
2. Wait for Kavita to identify that book as having been updated
3. The book will not appear in "Recently Updated" though if previously read to completion within the last x days, may appear in On Deck.

**Expected behavior**
The book to appear in the "Recently Updated Series" window.

**Desktop (please complete the following information):**
 - OS: Docker (Unraid, Slackware Linux)
 - Browser: Chrome 109.0.5414.120
 - Version: 0.6.1.0

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22+
 - OS: Android 13
 - Browser: Chrome Android

**Comment by majora2007** [comment]
Okay, sorry for the long wait, but it finally clicked what you're doing. You're updating an existing chapter (book) with new pages. This will not trigger the Recently Updated as that's not necessarily what it's capturing. It is instead for added entries into a series, rather than pages being added. If this is something you want, I'd request it on the feature site. I have big plans that I'm slowly working on for an overhaul on the dashboard system (but very slow due to the massive amounts of rework and design required).
