### ISSUE TITLE
Occasional "black sections" when using vertical scrolling in the reader with webtoons.

### ISSUE THREAD

**Issue by Dragonatorul** [Kareadita/Kavita#1848]
**Describe the bug**
Occasionally, when scrolling vertically in webtoons, a black rectangle pops-in on the top or bottom edge of the screen, which ever side is "unloading". As if the image is unloading before it would be entirely off-screen. 

This is often observed after switching applications, or putting the device to sleep/closing the screen. 

This is observed on an iPad 8 in Safari and an Android Samsung A70 device in Firefox.

**To Reproduce**
1. Access the website in a mobile device browser (iPad or Android confirmed)
2. Load a webtoon.
3. Change the reader to vertical scrolling
4. Scroll to ensure normal behavior is observed.
5. Minimize or switch window.
6. Browse other apps or websites.
7. Resume the minimized Kavita window.
8. Scroll will not show the black sections.

**Expected behavior**
Images should scroll smoothly off screen without any changes to the image visible on screen.

**Screenshots**

![video](https://user-images.githubusercontent.com/109987846/222916629-1abd05c0-a183-4ff9-ad64-f3a0889eeb10.mp4)

**Smartphone (please complete the following information):**
 - Device: iPad 8
 - OS: iPadOS 16.3.1
 - Browser: stock Safari
 - Version n/a

**Smartphone (please complete the following information):**
 - Device: Android Samsung A70
 - OS: Android 11
 - Browser: Firefox
 - Version 110.1.0

**Additional context**

**Comment by HubKing** [comment]
This happens very frequently in my case. I am using FireFox on Gnome (Linux), and this does not happen 100% of the time, but most of the time, it happens. I am also using webtoon mode with width-fit. If I scroll down, black area appears at the bottom of the screen and automatically disappears after 1~2 seconds. If I scroll up, the black area appears at the top of the screen. Very distracting.

When this happens, I have to either reload the page or exit the book and re-open the book to solve this problem, otherwise it persistently happens with scrolling.

**Comment by majora2007** [comment]
@HubKing those black areas you see at the beginning and the end of the book are in fact areas that you scroll into to move to the next or previous issue. They are designed that way so you don't have to leave the reader to continue reading or you have to open the menu.

**Comment by majora2007** [comment]
Looking at your video, you definitely have some sort of loading issue. I've never seen that before. What type of device are you using? Maybe you don't have enough RAM or you have a video card issue?

**Comment by HubKing** [comment]
> @HubKing those black areas you see at the beginning and the end of the book are in fact areas that you scroll into to move to the next or previous issue. They are designed that way so you don't have to leave the reader to continue reading or you have to open the menu.

It happens with a series of images that belong to the same "volume" (i.e., exist in the same directory), and sometimes that black area does not happen (at least for a while), and it seems that the problem does not happen in Chrome (although, I may need more testing to surely say that it does not happen on Chrome), so it is hardly believable that the black areas are intentional. Maybe you need to test it in FireFox, if you only tested it in Chrome.

Screen recording: Doing the same thing in Chrome.

[scroll-chrome.webm](https://user-images.githubusercontent.com/10900489/233838643-ed0de26e-b80b-4bd1-ac7a-9e2715ecdd16.webm)

**Comment by majora2007** [comment]
I validated just now in Firefox for some of my media and it indeed works fine. What it looks like is either a memory issue, like the images are too large and eating up too much memory (Kavita's webtoon reader only keeps 10 or so images in memory at once, so it shouldn't be an issue) or some other system issue, rather than my code's problem. 

Are you able to reproduce on our demo website? Can you list your browser's exact version? Please also mention your Kavita version to ensure you are on the latest (although the webtoon reader hasn't gotten an update in some time).

**Comment by HubKing** [comment]
It does not happen 100% of the time, even on FireFix; it happens randomly. Anyway, after a while, the problem also happened in the demo website, too. I recorded the screen, but the video file size was over 10MB and GItHub did not let me upload the video, and cutting the video length did not reduce the file size, so I had to re-encode the video, which took me a while.

https://user-images.githubusercontent.com/10900489/233844522-8bc1715d-2d50-428b-824d-881bdc21511f.mp4

Maybe some view settings are relevant whether it happens or not. If the demo user's setting is shared across sessions, then if you log in now and use the current settings, it should be the same as my case. If not, below are the view settings I used. The book I opened was "Give My Regards to Black Jack" volume 1.

![image](https://user-images.githubusercontent.com/10900489/233844287-934d1714-b1b4-4c45-9de7-9eeed3350019.png)

![image](https://user-images.githubusercontent.com/10900489/233844334-b6a381fb-7b0a-411e-8c5e-f613d84b3532.png)

My Kvita version is 0.7.1.4 (installed from AUR), and FireFox version is 112.0.1.

**Comment by majora2007** [comment]
The code is very straightforward. When you are seeing a long image like that, it is just that, an image on the screen, rendered as an image tag. The only thing that comes to mind is that the images are sent with Range processing, meaning they can be downloaded in chunks at a time by the browser, which you can see if you're on slow internet on non-webtoon mode. 

It's very interesting as I've never been able to reproduce this effect you all are seeing. For me, the reader is insanely fast and all images are rendered, no matter how fast or slow I scroll through it.

**Comment by HubKing** [comment]
Well, if this happens to a lot of other users, they will come to this thread and add their situations, which would help to find the steps. If not, then it is a rare case that you can ignore.

Anyway, I have been testing with settings to find a way to reproduce the problem, and it seems that "Save Globally" does not work. Or at least not in the way I expected from its name. In Settings -> Preferences -> Image Reader, I chose "Fit To Height" for Scaling Options. Then, I opened a book, clicked the bottom, clicked Settings, set "Width"  for Image Scaling, and then clicked Save Globally. I thought that it would update Settings -> Preferences -> Image Reader -> scaling Options to "Fit To Width", but it did not. In fact, if close the book and open the same book again, it is back to "Height". Is it functioning as intended? What does "Globally" mean, then?

**Comment by majora2007** [comment]
Create a new issue for support please. @HubKing

**Comment by majora2007** [comment]
I don't think so. The inital load takes take to cache the files in your config/ folder (unzip the file, etc). Afterwards, it is just an I/O operation. Unless your Kavita config/ folder is on a usb stick, you shouldn't see any issues there. 

The only areas I would think are the browser trying to free up memory, the browser having some rendering issue, or extreme memory limits causing some issues. 

For example, users mention seeing it when scrolling down. When that happens, if you've scrolled enough, we insert new images at the end. Perhaps that added memory causes a hiccup on the browser. 

I've tested this on a Fire 10 HD, my Pixel 3a, and multiple browsers from my PC and I'm not seeing the issue. I tried with HD Digital releases, proper webtoons, and non Digital releases to no avail of reproducing.

**Comment by HubKing** [comment]
> Could the lower performance of the "server"

My server has 16GB DDR3 and a 4c/8t Xeon processor, and the server and my client PC are connected via 1Gbps Ethernet (the same NAT). Considering that the server is doing not much more than just sending a few MB's JPG files, I doubt that the black bar appears for a second because of a slow server. 

Also, my client PC has a Ryzen gen2 processor, 32GB of RAM, RDNA2 GPU with 8GB VRAM. It probably is not because of a slow client, either.

**Comment by therobbiedavis** [comment]
I think this may be a hardware acceleration issue. https://stackoverflow.com/a/26682113
Try the following which will force hardware acceleration, worst case this would remove the browser as the performance bottleneck:
```
*:not(html) {
    -webkit-transform: translate3d(0, 0, 0);
    -moz-transform: translate3d(0, 0, 0);
}
```

**Comment by HubKing** [comment]
> I think this may be a hardware acceleration issue. https://stackoverflow.com/a/26682113 Try the following which will force hardware acceleration, worst case this would remove the browser as the performance bottleneck:
> 
> ```
> *:not(html) {
>     -webkit-transform: translate3d(0, 0, 0);
>     -moz-transform: translate3d(0, 0, 0);
> }
> ```

How to apply that exactly as an end-user?

**Comment by majora2007** [comment]
That's for me. I'll look into it and build a nightly. One of our nightly users was able to reproduce.

**Comment by therobbiedavis** [comment]
I have implemented the hardware acceleration code in the latest nightly build. If anyone is able to test and report back that would be great.

**Comment by majora2007** [comment]
While not exactly targeted, I did a lot of work recently in the webtoon reader. Would love if someone could test this on v0.7.14 and let me know if it's still happening. I still believe it's a browser issue, but I have a new virtualized scroller, so memory use should be less.

**Comment by Dragonatorul** [comment]
Thank you!

I had to temporarily drop Kavita while migrating servers because of some infrastructure issues, but I plan to reinstate it this week. I'll update here with my test results.

**Comment by Dragonatorul** [comment]
It seems to be working much better now. There is still a slight fraction of a second of a black section when scrolling a bit faster, but that's not that different from some other online readers. I suspect that's just loading the next image, but it is barely noticeable.

**Comment by majora2007** [comment]
Glad to hear this got fixed! Appreciate the retest.

**Comment by Dragonatorul** [comment]
> Glad to hear this got fixed! Appreciate the retest.

Thank you for your hard work on this!
