### ISSUE TITLE
Kavita ODPS structure

### ISSUE THREAD

**Issue by apiweb** [Kareadita/Kavita#1891]
**Describe the bug**
I've been using Kavita as an OPDS server for my comic collection and noticed that the current structure makes it difficult to access and read my comics.
Today you need to open navigate to each issue and open it individually. 

**To Reproduce**
1. Go to Server Settings
2. Enable ODPS
3. Navigate some libraries on the ODPS
4. Access some series
5. Access some issue
6. Now you are inside the issue, but you need to click on it individually again to access the issue itself.

**Expected behavior**
Opening every issue directly in the series folder rather than navigating to each release individually would be much more convenient.

**Screenshots**

https://user-images.githubusercontent.com/5881027/226476115-281a95ce-0ba2-4b66-ab46-cc0341fdc42e.mov

**Smartphone (please complete the following information):**
 **- Device:** iPhone 13
 **- OS:** iOS 15
 **- Browser:** Panels or any other ODPS navigator

**Additional context**
Another user on the Panels forum had the same problem. It looks like this is because of the way that Kavita structures the ODPS:
[Panels and Kavita structure](https://community.panels.app/t/panels-and-kavita-structure/1720)

---
I think to fix this bug. It will be good to combine the XML structure for the series with the issues, showing the issues of a series. This will enable you to access the issues directly from the series page.

XML structure for a series with their issues
<img width="1510" alt="Screenshot 2023-03-20 at 21 54 24" src="https://user-images.githubusercontent.com/5881027/226476957-61896285-592c-459c-a45f-6269c1cb55f9.png">

Issue individually
<img width="1510" alt="Screenshot 2023-03-20 at 21 54 49" src="https://user-images.githubusercontent.com/5881027/226476905-eb5cdf51-4cef-43e4-8bc9-354149428899.png">

**Comment by majora2007** [comment]
I appreciate your post, however this is not something I'm interested in enhancing. This doesn't allow for Volumes with multiple chapters. I've already flattened the OPDS layer and as of now, I'm satisfied with how it behaves. I am receptive to a PR if you would like to tackle it yourself.

**Comment by MadsMighty** [comment]
> I appreciate your post, however this is not something I'm interested in enhancing. This doesn't allow for Volumes with multiple chapters. I've already flattened the OPDS layer and as of now, I'm satisfied with how it behaves. I am receptive to a PR if you would like to tackle it yourself.

Please help me understand this: I imagine most people read their manga/comics while connecting to a reader app of some sort. Most readers are OPDS based. Every reader connecting to Kavita will need to click on Manga > Volume > Issue then >Issue again to read a single issue of something instead of the much simple Manga > Volume > Issue. Doing it this way does not "remove" Volumes being able to have multiple chapters since they can be parsed that way by the reader depending on if the media even *has* chapters.

This also breaks "continue reading" functionality in all OPDS readers since you have to back out two levels to find the next comic in the series you want to read, making it an all around more cumbersome and frustrating experience to read from Kavita VS other sources.

The Panels team has already denoted that this is something they cannot fix since it is based on how Kavita formats OPDS feeds. I can also confirm this behaviour is replicated in Chunky Reader as well.

With all of that, why would it not be worth enhancing this functionality so that the organization of Kavita is reflected the same on all levels? 

I really appreciate all of the work you've been doing, Kavita is close to the perfect solution for so many for comics reading, and I imagine this change would make a big difference for many people.

**Comment by MadsMighty** [comment]
Another potential suggestion: changing the OPDS feed based on library type. For example, Comics almost *never* have chapters, and flattening the OPDS Issue>Issue for that library type would preserve chapters for Manga that uses it
