### ISSUE TITLE
Can't parse certain special characters

### ISSUE THREAD

**Issue by JShiesty-dev** [Kareadita/Kavita#1986]
**Describe the bug**
Kavita seems to act weirdly with series with special characters like [ and ]. Ex. the series "[Oshi No Ko]"'s volumes and chapters all somehow become their own series. "[Oshi No Ko] - v01" becomes the series "v01" and so on. Seems like it can't parse the series name when it is wrapped in special characters.

**To Reproduce**
1. Create a folder "[Oshi No Ko]"
2. Add files "[Oshi No Ko] - v01", etc
3. Scan the library
4. See the series parsed incorrectly

**Expected behavior**
Series should be parsed properly as [Oshi No Ko]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
   Windows 11 [Docker]
   Chrome
 - Version [e.g. 22] (can be found on Server Settings -> System tab)
   Latest nightly

**Comment by majora2007** [comment]
Kavita strips certain characters out when filename parsing as certain characters are used to store arbitrary information like group or release type. [Digital] is a tag you see often. 

If you want to use these special characters you need to embed metadata with just the Series tag OR you can embed into the first file a series with brackets and a localized series of one without. Kavita will now group them together.

**Comment by GlassedSilver** [comment]
Maybe it would be wise to strip the parts between square brackets and such only if there is any other text in the folder or filename otherwise. Stylized titles are not that common, but thousands of users running into rare, but unexpected and maybe awkward to troubleshoot issues if they are less tech savvy may hamper the UX. At the very very least provide a warning to the user alerting them to such an oddly behaving folder being found and providing an actionable task from within Web UI maybe?
