### ISSUE TITLE
In 2-column mode,space between columns is too small 

### ISSUE THREAD

**Issue by samueler2016** [Kareadita/Kavita#2003]
In 2-column mode,space between columns is too small...

**Comment by majora2007** [comment]
This is not a valid issue. You didn't put any effort into this. Please use the template and try, otherwise I can't help you.

**Comment by samueler2016** [comment]
Hi Joe, I like Kavita and would like to see it gets better and better. And I know how to adjust the layout globally/one-on-one,but still feel it is a little messy...I spent a lot of time adjusting it...

**Comment by majora2007** [comment]
Okay but what do you want me to do. You're just saying fix this issue you have without any way for me to reproduce it, any insights into your system or device. 

That's why there is a template. I'm going to close this issue. Feel free to create an issue with the template, but without that I can't help you.
