### ISSUE TITLE
Files downloaded via OPDS are not renamed

### ISSUE THREAD

**Issue by random-human-being** [Kareadita/Kavita#2080]
When downloading (not streaming) a CBZ anrchive via OPDS, Kavita sends the file as it is in the filesystem, with its name unchanged.

Conversely, when downloading a file from the web interface, this is automatically renamed to e.g. "Series Name - Volume N.cbz".

I am assuming the latter is the intended behaviour, and that the former is an oversight.

Tested on 0.7.1 through 0.7.3 (Docker install) using Chunky Reader as client.

**Comment by majora2007** [comment]
I had originally left the OPDS implementation to download the raw files, as that is how it was designed for. I can give it the same implementation as using the web downloader if that makes it more consistent.

**Comment by random-human-being** [comment]
My concern is that the original filenames might give away information I don't want to share with people who use my server, e.g. the source of the files themselves.

Also original filenames can look a bit messy sometimes.

**Comment by majora2007** [comment]
That's fair. I'll take a look later, but letting you know it's low priority right now.

**Comment by majora2007** [comment]
I took a quick look into this. Here's the deal. Adding this renaming adds a bit of complexity. The issue is that something like Manga might work, we can rename it like the web, but books loose a lot of context, as in Kavita a book might be volume 1, but in the UI it's showing the full title. 

I feel like adding this actually makes the implementation worse. Adding all that logic to make it the best experience is also something I'm not interested in personally. If someone wants to try and tackle it, so be it, but it's not something I want to move forward with. Here is the needed code for OPDSController.DownloadFile():

```cs
var series = await _unitOfWork.SeriesRepository.GetSeriesByIdAsync(seriesId);
        var chapter = await _unitOfWork.ChapterRepository.GetChapterAsync(chapterId);

        var files = chapter!.Files;
        var (zipFile, contentType, fileDownloadName) = _downloadService.GetFirstFileDownload(files);
        var dlName = $"{series!.Name} - Chapter {chapter.Number}{Path.GetExtension(fileDownloadName)}";

        if (chapter.Number == Parser.DefaultChapter)
        {
            var volume = await _unitOfWork.VolumeRepository.GetVolumeAsync(volumeId);
            dlName = $"{series!.Name} - Volume {volume.Number}{Path.GetExtension(fileDownloadName)}";
        }

```
