### ISSUE TITLE
[Discussion] Using Task.WhenAll

### ISSUE THREAD

**Issue by senpai-notices** [Kareadita/Kavita#2306]
As per this [comment](https://github.com/Kareadita/Kavita/blob/8c7c01f745368c2229f35b8e4a22c5488367ddf1/API/Services/Tasks/ScannerService.cs#L530):
1. Are there any blockers to converting the for-loop to `Task.WhenAll`?
2. Should we consider a max concurrent ops amount so as to not overwhelm the DB? (Do we have any existing consts for this?)

**Comment by majora2007** [comment]
I have not looked into it since I made the note. From my experience, parallelism in the scan loop only causes resource exhaustion (given many people run low power machines with Kavita) or concurrency issues around some metadata, like people or genres. 

Are you suggesting you're looking into contributing something?

**Comment by majora2007** [comment]
Closing this down as I made the scan loop synchronous to solve a constraint issue in the DB due to some parallelization. This wont be needed to look at.
