### ISSUE TITLE
Files without numbers in file name do not get picked up

### ISSUE THREAD

**Issue by chrisadas** [Kareadita/Kavita#231]
Files without numbers in file name do not get picked up. This prevented single-file manga from being included during library scan.

Any numbers present in file name also assumed to be chapter name. 

## Process to reproduce

1. Have 2 files named "Eyeshield 21.cbz" and "Eyeshield.cbz"
2. First file picked up as Series: "Eyeshield", Chapter: 21.
3.  Second file does not get picked up.

## Expected result

I can't think of a good way to deal with "Eyeshield 21.cbz" yet, but for the case where there is no number at all, I expect it to be picked up and shown as individual work.

**Comment by majora2007** [comment]
Hi Chris, I have a case of this working on my machine, let me validate the rules and Ill get back to you this week.

**Comment by chrisadas** [comment]
Hi Joseph, thank you for the great software and for looking into this!

Please do not feel you need to implement this if it will mess with the use case of of majority of users. I am well aware this is a rather niche needs. I just tried adding a single 0 to a file name (Eyeshield 0.cbz) and that is already enough to get a file picked up as a special. It means 2 click to start reading instead of 1 click, but is not a big deal at all.

**Comment by majora2007** [comment]
I don't think it is a niche, I def can see this being more common, but as you mention, I might have to just inform users to rename. 

Please note, you can use the "Read" or "Continue" button to the right of the image which will automatically pick the best point to read from. So for you, you wouldn't have to deal with the tabs.

Also note, in this release, I will be changing the tabs so if you only have a special, it will automatically select the specials tab for you. 

Thanks for being understanding. I'll update you once I start working on this if I can accommodate, otherwise I'll close the issue.
