### ISSUE TITLE
issue numbers that aren't natural numbers

### ISSUE THREAD

**Issue by phatalx** [Kareadita/Kavita#2432]
Issues with non-standard numbering do not appear in the issues list or they do but are not in the right place.

1. Open any book with non-standard issue numbers
2. Click on the issues tab
3. 
3a. The issues are not present in the list (#-1, #½, # 20.INH); Daredevil (1964) is a good example of -1, Daredevil (1998) for #½, Iron Man (2013) for # 20.INH.

Volume has -1 cover
![image](https://github.com/Kareadita/Kavita/assets/15606205/d9202624-9454-464d-9853-3a76f6df1dda)
![image](https://github.com/Kareadita/Kavita/assets/15606205/2bc66c3d-8925-4a2d-a01d-1925282771e1)
Issue -1 is not in list.
![image](https://github.com/Kareadita/Kavita/assets/15606205/634952fd-9742-428f-919f-6f83605a4d7a)

OR
3b. The issues are present (# 1.50) but are sorted according to their issue number rather than published date. Daredevil (2014) is a good example of this where issue 0.1 was published on the same date than issues 5 and 6 but appears before # 1.

![image](https://github.com/Kareadita/Kavita/assets/15606205/f52fc485-1245-4d93-bda8-9542aaeba8f3)

- Ideally the issues would all appear in the issue tab and be in the correct reading order (according to published date then issue number).

Versions
 - OS: TrueNAS-SCALE-22.12.3.3
 - Browser Firefox Browser 119.0.1 (64-bit)
 - Version 0.7.8.1

Additional context:
Comics scraped with comicvine information sometimes use issue numbers that aren't your standard natural numbers. 
- Some issues use decimal numbers # 1.50 for in-between or prequel issues. These issues appear but are ordered using the issue number and thus do not always match the reading order.
- Some issues use negative numbers #-1 for flashback issues. These issues do not appear in the issue list but are still considered as first in ascending order for the volume and thus change the volume's cover image as well as are accessible to read when clicking the volume containing the issue but completely break the navigation (moving from one issue to the next).
- Some issues use some fraction such as #½ notably for Marvel issues with the Wizard magazine tag. Can't see or read these.
- Some issues have characters such as # 5AU or # 20.INH that are either appends or sequels. Can't see or read these.

**Comment by majora2007** [comment]
So this is something that was brought to my attention much after Comics were added and I'm not sure yet how to solve it, since Comics seem to have random rules for issue numbers but yet they need some sort order. Ideally, it would be nice if ComicInfo could support this with a field, but the spec is kinda frozen.

There is a feature request here that you can upvote and copy/paste some of the data to. 
https://feats.kavitareader.com/posts/396/improved-parsing-for-western-comics-library-comics

At the moment, I do not have a good solution to fit this into Kavita's model since we use issue numbers as numbers and not strings with some arbitrary order (like ½ wouldn't actually order between 1 and 2 using a string sort, it would have to be custom coded). 

It is something I am aware of, but again, non-trivial to support and refactor major parts of Kavita for.

**Comment by DieselTech** [comment]
Updated link for discussion around better comic support: 

https://github.com/Kareadita/Kavita/discussions/2542

**Comment by flips22** [comment]
One additional item in this area is how to handle the cover image for the series. Right now it pulls a 0.5 issue for the cover, but I think in the vast majority of the cases the cover image for the volume should be issue #1. In the example above, the iconic cover for issue #1 from 1964 should be shown instead of a flashback issue from the 90's.

**Comment by majora2007** [comment]
@flips22 thanks for bringing that to my attention. I took care of it in the preliminary work to accomplish the comic rework.

**Comment by DieselTech** [comment]
The ComicVine library type has been added as of version 0.7.12. That library type should resolve situations like this. 

If there is any problem using the new library type, please open a new issue.
