### ISSUE TITLE
Sidenav disapears after creating a new account then logging back into admin account

### ISSUE THREAD

**Issue by kuroikana** [Kareadita/Kavita#2453]
After creating a new account, return to Admin sidebar lost
![`Y1~2L V4`Y`}4KM 2 62GP](https://github.com/Kareadita/Kavita/assets/103518535/9d7e967e-fb33-4511-bc4b-1916fa47affe)
![X5 2YIT_SD~RODZBD$LPC6H](https://github.com/Kareadita/Kavita/assets/103518535/d7731be4-7542-4080-bc38-493b0fd85f3a)

**Comment by majora2007** [comment]
Please attach logs when you perform this flow

**Comment by majora2007** [comment]
I'm not able to reproduce. On the lastest nightly, these are my steps:
1. Login as admin
2. Invite a new users and give access to 1 library
3. Log out
4. Setup user's account
5. Log into my admin account

All my libraries are present. 

I also tried:
1. Login as admin
2. Invite a new users and give access to 1 library
3. Log out
4. Setup user's account
5. Log into user account, confirm only 1 library
6. Log out and back into admin.

**Comment by majora2007** [comment]
Please provide more information like the template asks. What version are you reproducing this on? What version did you update from or did you recently start on the latest? Please attach logs for me.

**Comment by robertnsu** [comment]
I've experienced this bug too, but I spun up another instance and I'm unable to reproduce it.  I looked inside the database and noticed that the records in `AppUserSideNavStream` that should be there are missing for my account.  There are other accounts in the installation that are unaffected.  Once I get home, I'll attach logs and screenshots.

Is there something I should grep for specifically?  I have about a weeks worth of log files since this happened.

**Comment by Optekah** [comment]
This just happened to me. Brand new to Kavita. Made a second account, logged back into Admin, and poof. Can't see any of the collections I made. Side navigation bar is just missing content unfortunately rendering it unusable for me.

OS: Unraid 
Kavita: 0.7.11.1
Docker Image: lscr.io/linuxserver/kavita

**Comment by majora2007** [comment]
I was able to reproduce finally. I will get this fixed for the upcoming hotfix before I end the year out.
