### ISSUE TITLE
Allow change of default port

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#256]
Through the Server Settings or appsettings.json, the admin should be able to change the listening port of the application. Manual reboot is required. 

Docker users should not be allowed to change it from 5000. UI should be disabled and inform them.

**Comment by klansimpson** [comment]
I assign each of my Docker images their own IP on my network, typically then set them to port 80 so it just works via IP (no port needed as 80 is the default for http). I CANNOT change the IP as its locked down due to being Docker, and I cannot assign the port properly via the compose.... Can you please give us a "warning if you are running docker changing this port can break your configuration" option tick box slider, or something. PLEASE

Honestly it is this sort of thing that makes the app too much of a headache when you have literally 30 apps running and have to remember a port number for each.

I get it though if they are all running on the same IP makes sense.... but mine AREN'T and not being able to customize something so simple on something running on my own hardware is sort of bonkers frankly lol

**Comment by scare376** [comment]
part of the whole point of docker is that you can have the external mounts different from the internal. if how you've been setting up all of your other containers has been working you should be able to point 5000 internally to 80 externally and it should work fine.

**Comment by klansimpson** [comment]
Sadly you cannot dictate the port via docker compose if you give it it's
own IP address (annoyingly). Luckily usually you can set the port in the
config file of said app. Obviously if run your docker via bridge (all on
the same IP) you would need to be careful re ports being unique and
specifically match up the port to the apps config. If you use MacVlan you
don't, and it's like the docker app is it's own machine on your network.

It just seems a shame that I would have to share the IP of the host to be
able to dictate the port, and wouldn't be able to use Port 80 as the host
is using it.

This is the only docker setup I have come across where you CAN'T set the
port
