### ISSUE TITLE
Missing Localization Strings

### ISSUE THREAD

**Issue by gregory-open** [Kareadita/Kavita#2709]
### What happened?

Several strings are not translated in my language (fr) whereas traduction is correct in weblate:

- Statistics > Total Genres
- Statistics > Recently Read
- Satistics > All Users (filter) <== string not found in weblate 
- Title of the jobs in the cron

Check Updates 	— 	0 */1 * * *
Cleanup 	— 	0 0 * * *
Remove From Want To Read 	— 	0 0 * * *
Scan Libraries 	— 	0 0 * * *
Backup 	— 	0 2 * * *
Update Yearly Stats 

### What did you expect?

String translated in the local language

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Hello. Translations strings aren't flushed to Kavita in real time. They are released to the stable on each release. So if these were recently updated, then they might not be in the Stable.

However, I do know that french hasn't gotten any updates since the stable. So, you can try running the cache busting task yourself to see if it clears up your Statistics issues. 

The Tasks with the cron notation aren't actually translated. I'll make sure they get included in localization.

**Comment by gregory-open** [comment]
Hello,
I refreshed with the reload cache but no better.
In fact, I've done a number of translations for the French language and I've gotten into the habit of doing updates right after the latest version comes out;
I think for the first string, I translated them right after the previous stable version was released.

**Comment by gregory-open** [comment]
To be more clear, I have run the task to clean the local cache

**Comment by majora2007** [comment]
Okay sorry, I misunderstood the issue. I looked at the code and noticed that a few places were missing localization and some keys were localized but not hooked up. 

I'll take care of them all. Thanks for bringing it to my attention.

**Comment by gregory-open** [comment]
No problem.
Thank you!
