### ISSUE TITLE
Images in EPUB formats show as blank when using dark, black, or white backgrounds.

### ISSUE THREAD

**Issue by ice45core0** [Kareadita/Kavita#2723]
### What happened?

![image](https://github.com/Kareadita/Kavita/assets/29149528/6fdc4187-f019-462c-8d18-3ff6de04894b)
![image_2024-02-16_164413659](https://github.com/Kareadita/Kavita/assets/29149528/6b4ab181-643a-40cd-a8cd-1ba5c93fb02e)

I have some manga saved as EPUBs. When I open them in the kavita reader, the cover loads in, but the rest of the pages appear blank unless I am using the "paper" background. These files work fine in other apps, I'm only facing this issue with the kavita EPUB reader. I've also tried other browsers and devices and still face the same issue. 

### What did you expect?

Have the pages be visible regardless of what background is selected.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox, Chrome

**Comment by dmadisetti** [comment]
I didn't even realize images were possible because I only use the dark mode version. Guess I'll swap to light mode for now

**Comment by dmadisetti** [comment]
Realized this is due to baseurl not being respected in my vase

**Comment by majora2007** [comment]
Are you implying there was an issue Kavita side or a user error? If base url isn't respected, please make sure it's configured within Kavita.

**Comment by dmadisetti** [comment]
I will start another issue if you want- it is Kavita side - despite having baseurl set, the dark theme still points to 127.0.01

**Comment by dmadisetti** [comment]
![image](https://github.com/Kareadita/Kavita/assets/2689338/e3108bd9-60fa-4eb9-8bbb-8f4647953294)
![2024-03-05-185538_820x597_scrot](https://github.com/Kareadita/Kavita/assets/2689338/e4d94804-30c3-47f9-9bcf-b0c829fb32ab)

kavita-backend-0.7.1.4

**edit:**

Also, from main.js

{production:!0,apiUrl:"/api/",hubUrl:"/hubs/"}}

I also tried restarting the service

**Comment by majora2007** [comment]
This issue is fine, I wasn't understanding. I'll take a look. 

What is the base URL settings?

**Comment by dmadisetti** [comment]
Does hostname not change that?

**Comment by majora2007** [comment]
I'm not sure off the top of my head, I'd need to look. I believe that it does not. I believe it pulls from how you're accessing the server. So if you're using a reverse proxy (and the correct headers are forewarded), then it will work. Otherwise if you're using localhost (which is what it looks like), it will just use localhost (why go over the network for no reason?). 

But you mentioned earlier base url, hence why I'm asking about the base url to try to reproduce it.

**Comment by dmadisetti** [comment]
I'm hitting the page via https://kavita.ave, I have nginx set up to just pass upstream, so should preserve headers, and hostname is set.

I just checked the documentation again; I think there's a bit of inconsistency between hostname and base url. Host name is listed in settings (see screenshot above), but baseurl is listed in the docs: https://wiki.kavitareader.com/en/guides/settings#base-url

**Comment by scare376** [comment]
Well host name and baseurl are 2 different things. For example you could have kavita.domain.com as the hostname while instead you may want to do domain.com/kavita. This second we call a base URL because it uses the main domain as the hostname and building off of /kavita

**Comment by scare376** [comment]
You may want to take a look at #1183 and the nginx examples in the wiki.

**Comment by dmadisetti** [comment]
Ok, my header **was** off. That fixed the image issue for me, epubs are fine now

**Comment by scare376** [comment]
Is this completed? The person who opened the issue hasn't said anything.

**Comment by ice45core0** [comment]
I renamed the .epub files to .zip and have been using them that way as a workaround since it displays with using a different reader, but the original issue is still not resolved.

**Comment by majora2007** [comment]
@ice45core0 can you please provide information that can help us debug your situation? 

For example, how are you accessing Kavita? Localhost, reverse proxy?

Would you be able to DM me the epub via Discord?

**Comment by ice45core0** [comment]
I have Kavita running on my home server. I've tried accessing it using the local ip address and through a reverse proxy, same result for both. I sent you the file I was testing in the pictures above.

**Comment by majora2007** [comment]
Okay I took a look at the epub. Usually with these types of issues, it's due to the css within and this is no different. This epub seems to be designed to work in a very specific reader as there is a ton of custom styles to render the images in a certain way and provide zoom functions for said reader. 

I'm not sure this is something Kavita can "support" as it goes against the norm and Kavita tries to preserve the inner css of the book. 

However, this file you have is just a manga. You would be advised to extract out the images and put in a cbz (this way you can tag with MangaManager to have metadata) or just rename to .cbz and tag your file. Epub is for text documents with mixed images. If you just have pure images (which is what this manga is), then you are better off using an image-based reader, which is what the archives open in.
