### ISSUE TITLE
Passwords can't be reset if e-mail isn't setup

### ISSUE THREAD

**Issue by jader9920** [Kareadita/Kavita#2831]
### What happened?

Forgot admin password and when completing the forgot password flow and error message states "Email is not enabled on this server. You cannot perform this action"

### What did you expect?

I expected to be able to pull the password reset link from the system log.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Okay I thought this was a bug, but I actually made a decision to not enable this flow. I'll need to think of an alternative way to implement in case the admin forgot their stuff and don't use an email with their instance (not that email is used in any way other than within Kavita). 

Something like an alternative api call (but there can be security concerns with that).

**Comment by York-Lucis** [comment]
Any update on this subject? Or ideas of how could we "workaround" this particular problem, just for now? I've been unable to login on my admin account for some time due to the same circunstances, i would love to resume from my last read chapter ):
Sorry that i cannot be of any more help on the scope of this situation.

Thanks.

**Comment by majora2007** [comment]
@Eboraci did you try the flow on v0.8.1? I believe I tweaked the logic to drop a URL in logs but reject the UI flow

**Comment by majora2007** [comment]
Okay I confirmed I did not update this yet. This is due to the complexity. I will take this up for v0.8.2 as it's pretty common for admin's to forget their own password (use a password manager).

**Comment by York-Lucis** [comment]
Sorry for the delayed response, forgot to reply on your comment, but yes, there no such thing in the logs folder.

About the password manager, i use on every single *non-local* application, i did not used in this one specifically since its local and, since it never asked for my password for more than one time (when i was using it daily for +- 30 days), i eventually forgot that it was ever needed.

Thanks for understanding the situation and for the consideration of rolling this to v0.8.2.

**Comment by therobbiedavis** [comment]
One enhancement that could be done as like an "all else fails" is if in the db the password is set to something like "reset" manually, then when Kavita is started it could check and overwrite those with random passwords and dump the username and new password in the logs.

**Comment by York-Lucis** [comment]
Thanks, keep up the good work!

**Comment by majora2007** [comment]
Please note that this will release with v0.8.2. If you want to validate it yourself or provide feedback, you can on the nightly docker (don't use your main instance as there are db changes that make rolling back problematic)

**Comment by DLBPointon** [comment]
Just messaging to say thanks for the update on nightly. The reset pass works great.

**Comment by Slava-On** [comment]
Hello.

Can someone tell me how to do it, please?

***
_I expected to be able to pull the password reset link from the system log._
***

I am facing the same situation... How do I reset the password if the email has not been setup?

**Comment by majora2007** [comment]
> Hello.
> 
> Can someone tell me how to do it, please?
> 
> _I expected to be able to pull the password reset link from the system log._
> 
> I am facing the same situation... How do I reset the password if the email has not been setup?

Like the toast says, a link will be dumped into the logs. Use that link to complete the flow.
