### ISSUE TITLE
HTML format errors occur when sending emails with custom email templates

### ISSUE THREAD

**Issue by codenamek83** [Kareadita/Kavita#2859]
### What happened?

As shown in the screenshot, the content or body of the email notification appears to be malformed when using a custom email template. It seems that the custom template is being nested or encapsulated within another primary email template. This undermines the ultimate purpose of the custom notification templates. As discussed in Discord, I was unable to locate the base.html in the persistent volume of the container.

The contents of the templates folder on the host are as follows:
```
./config/templates/EmailConfirm.html
./config/templates/EmailPasswordReset.html
./config/templates/EmailChange.html
./config/templates/SendToDevice.html
./config/templates/EmailTest.html
```

The contents of the templates folder on the container are as follows:
```
./app/kavita/EmailTemplates/EmailConfirm.html
./app/kavita/EmailTemplates/base.html
./app/kavita/EmailTemplates/EmailPasswordReset.html
./app/kavita/EmailTemplates/EmailChange.html
./app/kavita/EmailTemplates/SendToDevice.html
./app/kavita/EmailTemplates/EmailTest.html
./config/templates/EmailConfirm.html
./config/templates/EmailPasswordReset.html
./config/templates/EmailChange.html
./config/templates/SendToDevice.html
./config/templates/EmailTest.html
```

I've upgraded to the latest version of Kavita, v0.8.0, from v0.7.14.

![Screenshot from 2024-04-13 21-47-10](https://github.com/Kareadita/Kavita/assets/151714891/8cedcbba-cc0d-45a2-8f37-1a19e31d63e7)

### What did you expect?

I suspect that the email formatting is incorrect, which undermines the purpose of the custom email template.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox, Chrome

**Comment by majora2007** [comment]
Okay took a brief look. Here is what happened. I rolled out Email templates into Kavita. Then later I restructured code to use a base.html template. That file isn't in config/ because it wasn't there for the original migration. 

I can't write files after the fact to config/templates as it might affect a server admin's changes. So you just need to copy it yourself. There is a log statement too warning you:
`_logger.LogError("Customized Templates is on, but template {TemplatePath} is missing", fullName);`

You can find the email templates in EmailTemplates/

This will be my position going forward. If I add new emails, it is on the admin's who are using customized templates to copy them over and provide their customization on top.
