### ISSUE TITLE
Certificate error for e-mail

### ISSUE THREAD

**Issue by RumenBlack84** [Kareadita/Kavita#2895]
### What happened?

I am trying to use my protonmail bridge to send e-mails. However due to the nature of how the bridge works it's certificate is invalid for external use. Due to this invalid certificate I cannot send emails using kavita. Is there a way to bypass the certificate check for sending e-mails?

I'm not sure if this would be considered an issue report or a feature request.

### What did you expect?

A method to bypass certificate checking for sending emails.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by DieselTech** [comment]
There is no concept of certificates in Kavita for email. That sounds like something specifically for proton bridge that would need to be configured.

**Comment by nachfuellbar** [comment]
I've gotten a similiar error with my own Mail Server.
In Kavita's log i got this error. Seems like it wants a CRL even if the certificate is in the trust store.
The second error with self signed certificate is possibile to mitigate when importing the certificate of the CA.

I don't know if it's the same for protonmail bridge but as far as i can see (without actually testing) the issue should be the same.

```
The server's SSL certificate could not be validated for the following reasons:
 • The server certificate has the following errors:
   • unable to get certificate CRL
   • unable to get certificate CRL
 • The root certificate has the following errors:
   • self signed certificate in certificate chain
```

PS: would be great to have an possibility to disable the certificate check for Mail Server as they often use self signed ones (even in the internet)

**Comment by nachfuellbar** [comment]
As far as i can see, this application uses Mailkit
https://github.com/Kareadita/Kavita/blob/develop/API/Services/EmailService.cs#L293

In Mailkit itself there is a document for SslHandshakeException
https://mimekit.net/docs/html/T_MailKit_Security_SslHandshakeException.htm
where is following written:

Often times, mail servers will use self-signed certificates instead of using a certificate that has been signed by a trusted Certificate Authority. When your system is unable to validate the mail server's certificate because it is not signed by a known and trusted Certificate Authority, this exception will occur.

You can work around this problem by supplying a custom [RemoteCertificateValidationCallback](https://docs.microsoft.com/dotnet/api/system.net.security.remotecertificatevalidationcallback) and setting it on the client's [ServerCertificateValidationCallback](https://mimekit.net/docs/html/P_MailKit_MailService_ServerCertificateValidationCallback.htm) property.

**Comment by majora2007** [comment]
Based on the information, I would say this is more akin for a Feature Request.
