### ISSUE TITLE
Kavita API miss bcmap for PDF.js with Japanese PDFs.

### ISSUE THREAD

**Issue by kmt-t** [Kareadita/Kavita#2970]
### What happened?

Kavita generated the following log when processing Japanese PDFs:

> kavita | [Kavita] [2024-05-26 09:17:53.741 +00:00 13] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /kavita/assets/cmaps/Adobe-Japan1-UCS2.bcmap responded 404 in 0.1589 ms

The API URL "/kavita/assets/cmaps/Adobe-Japan1-UCS2.bcmap" appears to be incorrect, and the correct API URL is likely "/kavita/assets/cmaps/Adobe-Japan1-UCS2". This error is probably the cause of some Japanese PDFs not being displayed.

### What did you expect?

Upon checking with curl, the following log should be generated:

> kavita | [Kavita] [2024-05-26 09:28:04.923 +00:00 45] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /kavita/assets/cmaps/Adobe-Japan1-UCS2 responded 200 in 2.5314 ms

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
This looks like it's probably an issue with the PDF library we use: 
https://github.com/stephanrauh/ngx-extended-pdf-viewer

As this is automatic code outside of my control. You can create an issue over there and link here. Either some issue with your PDF or a bug in the library (especially if it doesn't open when it does in plain FireFox).

**Comment by kmt-t** [comment]
![firefox_vs_kavita](https://github.com/Kareadita/Kavita/assets/4026663/f735b5a8-5bff-4d7f-974d-9d231edc38f6)


I tested the problematic PDF in Firefox and encountered no issues.

I will create an issue with a link to the URL. However, please check the API URL routing on the Kavita side. I noticed a bcmap file with the bcmap file extension exists in the wwwroot directory.

**Comment by stephanrauh** [comment]
It seems your installation puts the files into the wrong folders. There's a property to configure the file of the CMAP files (`pdfDefaultOptions .cMapUrl`), but I suppose it's besser to investigate why the file is copied to the root folder instead of the assets folder.

Please tell me when you've manage to solve the issue so I can close the ticket in my ngx-extended-pdf-viewer repository.

**Comment by kmt-t** [comment]
Is the installation causing a problem?

My appsettings.json file is as follows, and I have changed the base URL:

> xxx@xxx:~/docker/kavita/data$ cat appsettings.json
> {
>   "TokenKey": "*****",
>   "Port": 5000,
>   "IpAddresses": "0.0.0.0",
>   "BaseUrl": "/kavita",
>   "Cache": 50,
>   "XFrameOrigins": "SAMEORIGIN"
> }

My docker-compose.yml file is as follows:

>xxx@xxx:~/docker/kavita$ cat docker-compose.yml
>version: '3'
>services:
>    kavita:
>        image: jvmilazz0/kavita:0.8.1
>        privileged: true
>        container_name: kavita
>        volumes:
>            - ./books:/books
>            - ./data:/kavita/config
>        ports:
>            - "5000:5000"
>        restart: unless-stopped
>        environment:
>          - LANG=ja_JP.UTF-8

The errors in the browser are as follows:

![error_on_browser](https://github.com/Kareadita/Kavita/assets/4026663/153b481d-0e33-4517-b8db-d5c6176233e6)

**Comment by kou029w** [comment]
It appears that UseStaticFiles returns a 404 error because the FileExtensionContentTypeProvider does not support the .bcmap file format.

=> https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-8.0#non-standard-content-types UseStaticFiles
=> https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs FileExtensionContentTypeProvider

The workaround is this:

```diff
diff --git a/API/Startup.cs b/API/Startup.cs
index a7eb490d..d86f47e5 100644
--- a/API/Startup.cs
+++ b/API/Startup.cs
@@ -356,9 +356,12 @@ public class Startup
 
         app.UseDefaultFiles();
 
+        // https://github.com/Kareadita/Kavita/issues/2970
+        var contentTypeProvider = new FileExtensionContentTypeProvider();
+        contentTypeProvider.Mappings[".bcmap"] = "application/octet-stream";
         app.UseStaticFiles(new StaticFileOptions
         {
-            ContentTypeProvider = new FileExtensionContentTypeProvider(),
+            ContentTypeProvider = contentTypeProvider,
             HttpsCompression = HttpsCompressionMode.Compress,
             OnPrepareResponse = ctx =>
             {
```

![image](https://github.com/Kareadita/Kavita/assets/1730234/8fe14593-da8d-470d-a854-e3ef25728f5d)

```
$ curl -I http://localhost:5000/assets/cmaps/Adobe-Japan1-UCS2.bcmap
HTTP/1.1 200 OK
Content-Length: 40951
Content-Type: application/octet-stream
Date: Mon, 27 May 2024 02:05:33 GMT
Server: Kestrel
Accept-Ranges: bytes
Cache-Control: public,max-age=1.00:00:00
ETag: "1daafd712da3877"
Last-Modified: Mon, 27 May 2024 01:42:03 GMT
X-Robots-Tag: noindex,nofollow
```

![image](https://github.com/Kareadita/Kavita/assets/1730234/9a581bc0-7f1b-4cc2-9c7e-8ea1451ff1ae)

EDIT: problematic book

=> https://www.soumu.go.jp/johotsusintokei/whitepaper/ja/r04/pdf/01fuchuu.pdf 『情報通信白書・ICT白書』令和4年版 資料編,総務省. Refer to page 1 of 01fuchuu.pdf. "付注" © [MIC](https://www.soumu.go.jp/english/) [CC BY 4.0 Deed](https://creativecommons.org/licenses/by/4.0/deed.ja)

**Comment by majora2007** [comment]
Can you please email or dm me the book?

**Comment by kmt-t** [comment]
@majora2007 

I sent problematic PDF by e-mail.

**Comment by majora2007** [comment]
Received. I'll work on this soon. I'm currently without power due to a big storm hitting Texas.

**Comment by majora2007** [comment]
Okay was able to reproduce and it does look like an issue with packing. Let me investigate `pdfDefaultOptions.cMapUrl` or why the files are being copied to root, as I was not aware of this issue.

**Comment by kmt-t** [comment]
Strictly it bcmap is located '/kavita/wwwroot/assets/cmaps/'.

>root@503d34758013:~# ls -la /kavita/wwwroot/assets/cmaps/Adobe-Japan1-0.bcmap
>-rw-r--r-- 1 root root 225 Apr 22 20:22 /kavita/wwwroot/assets/cmaps/Adobe-Japan1-0.bcmap

I apologize for my lack of proficiency in English and any inconvenience it may cause.

**Comment by majora2007** [comment]
I've already fixed this, just not pushed up yet.
