### ISSUE TITLE
When downloading using opds, the author is not listed

### ISSUE THREAD

**Issue by KeePach** [Kareadita/Kavita#2984]
### What happened?

I use comictagger to put metadata in the cbz's of my manga, all of them have the metadata of authors, like writer, artist, etc, but when using koreader OPDS and dowloading a book to read on the kindle, it always download with an "unknown author" as the first thing on the name

https://imgur.com/a/Om0YOM9

### What did you expect?

that the author should be filled and not unknown

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

using kavita in windows and koreader in a kindle

**Comment by kevindherdt** [comment]
Having the same problem right now but I have it with epubs.

Filenames when downloaded are like this.

Example

Unknown Author - Orc Eroica - Orc Eroica _Vol.1.epub 

Weirdly enough the metadata is correct inside the file so when looking at it everything is included but the filename of the download itself is wrong.

I can sadly not provide logs right now since I am on holiday on the other side of the planet at this time.

However I would like to add that this does not happen with every single app that downloads via opds.

Problems arise so far with

- Koreader. #Metadata correct but filename displays unknown author
- Alreader X pro #Filename correct but displays unknown author
- pushread opds #Works ok but filename contains a lot of %20 


Everything works correctly with 
- Moonreader #Downloads filename correct, displays metadata correct.. using this as the downloader now and reading it with koreader afterwards on boox device, but since I also have a Kobo I would prefer koreader to be usable for download too since I cannot use Moonreader on that.


Checking what little I can check I am thinking that it is not kavita doing something wrong but the opds implementions on the different apps not working the same? 

Edit.

I have a backup calibre-web running and just added opds to koreader and from there I can download it correctly the filename and metadata.
Also tested with alreader and Moonreader, all worked successfully.



Even though I use calibre to manage all my books on my desktop PC I use it to for good metadata tagging, I then embed the metadata into the files and and then robocopy the calibre libraries to the server,  there I just point kavita towards the calibre libraries and everything gets perfectly imported by kavita.

Note however that embedding the metadata with calibre is essential for kavita to be able to do what I want.

I prefer to have kavita instead of calibre or calibre-web because I have seperate libraries for light novels, fiction books and non fiction etc.

Only a minor issue but something is making some apps not able to read the author properly when using kavita opds.. except for Moonreader somehow

**Comment by majora2007** [comment]
I took a look and realized that author wasn't sending with the individual entries.
