### ISSUE TITLE
Kavita still tries to run as root despite setting a user 

### ISSUE THREAD

**Issue by UntouchedWagons** [Kareadita/Kavita#301]
I try to have all my docker containers run as a non-root user for better security, read/write access to my NAS and for simplified backup. However I'm unable to get Kavita to run as my go-to user

	$cat docker-compose.yaml
	version: '3.9'
	services:
	  kavita:
		image: kizaing/kavita:latest
		container_name: kavita
		user: "1000:1000"
		volumes:
		  - /mnt/data:/mnt/data
		  - ./appdata/kavita:/kavita/data
		ports:
		  - "5000:5000"
		restart: unless-stopped
		environment:
		  - PUID=1000
		  - PGID=1000
		  - TZ=America/Toronto

For my other containers setting the user via `user` or by using the PUID and PGID environment variables works, but not for your docker container. Could you fix this please?

Thanks

**Comment by therobbiedavis** [comment]
By default docker runs every container at root level. The linuxserver.io group implemented a script that changes the permissions according to PUID and PGID on container initialization, this is not something every container does. https://docs.linuxserver.io/general/understanding-puid-and-pgid

That being said, we do plan to implement this ability in the future, but there are several other features planned to implement ahead of it.

Since you said you try to runyour containers as non-root, it may be beneficial for you to look into running your docker daemon as non-root as documented: https://docs.docker.com/engine/security/rootless/

**Comment by UntouchedWagons** [comment]
Ironically rootless docker creates more permission issues as it does UID/GID mapping stuff instead of just using my user's uid and gid.

**Comment by DebugDax** [comment]
> By default docker runs every container at root level. The linuxserver.io group implemented a script that changes the permissions according to PUID and PGID on container initialization, this is not something every container does. https://docs.linuxserver.io/general/understanding-puid-and-pgid
> 
> That being said, we do plan to implement this ability in the future, but there are several other features planned to implement ahead of it.
> 
> Since you said you try to runyour containers as non-root, it may be beneficial for you to look into running your docker daemon as non-root as documented: https://docs.docker.com/engine/security/rootless/

This is also an issue for my docker setup. I have plenty of other contains that respect user: and the env PGUID/PUID to run with the correct permissions. This is the only container i've come across that won't run outside of root and because of this I can't modify the library folder to manage the contents. Could you elaborate on why it's marked as `wontfix` and you won't give users the options to run it with the permissions they want instead of always root, when previously it was mentioned "we do plan to implement this ability"?

**Comment by majora2007** [comment]
I don't use docker. It seems like a small user set that needs this. If you want to try and tackle it, feel free, but I personally am not going to be looking into it.

**Comment by zgjimgjonbalaj** [comment]
Anyone get this to work? I also am trying to run this in non-root so I can attach filebrowser to it safely. My goal is to upload books to Kavita without having to scp/ssh to it. Tried sharing a volume with a Nextcloud container so I can have books there but the UID:GID mismatch makes that problematic. The inability to upload books directly is kind of the limiting factor so am attempting workarounds but no luck.

**Comment by majora2007** [comment]
This was solved and then removed by the Kavita team as it broke one of our supported platforms (unraid maybe?). 

https://github.com/Kareadita/Kavita/pull/1649/files for the implementation. You can also look at the lsio container which has it setup as non-root as well.

**Comment by zgjimgjonbalaj** [comment]
Thanks for following up and sharing. To me, unless I am missing something it looks like maybe a conditional would help there. Something like If a UID & GID is provided via env vars **_then_** proceed with running as that UID:GID otherwise run as root.

I may create a PR at some point and test but for now and anyone else who needs this I was able to just run the lscr.io/linuxserver/kavita:latest image from linuxserver which allows you to pass env vars to set the user like so:

```
services:
  app:
    image: lscr.io/linuxserver/kavita:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
```
