### ISSUE TITLE
When the title and volume are both the same, they will be merged together

### ISSUE THREAD

**Issue by wind-chant** [Kareadita/Kavita#3115]
### What happened?

This is a very unexpected issue, and shouldn't even be considered a bug,  raised this issue to inquire if there is a way to avoid this problem.
Here is an example:
[Silk V2015](https://comicvine.gamespot.com/silk/4050-80116/)
[Silk V2015](https://comicvine.gamespot.com/silk/4050-86251/)
Both of them have the title "Silk" and were released in 2015. But they have different CVDB and are apparently two comics
they're merged together Is there any way to fix this, I wonder if it's possible to show both comics at the same time without changing the CVDB for the cbl lists
(also, what's the difference between a Comic and a Comic Vine, the page in the wiki hasn't been edited yet)

### What did you expect?

All the two comics can be display

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by wind-chant** [comment]
This is another example, and you can also refer to it for reference.
[Spider-Gwen](https://comicvine.gamespot.com/spider-gwen/4050-85311/)
[Spider-Gwen](https://comicvine.gamespot.com/spider-gwen/4050-80298/)

**Comment by Cducharme84** [comment]
Hi, the CV library type was setup to avoid the switching you're describing, it appends the volume to the series name (for example if tagged with start year as volume those Silk volumes would read as "Silk (2015)") to prevent the very stacking you're describing. Unfortunately Marvel has a horrible habit of starting multiple volumes of the same comic in the same year. 

To truly differentiate them you may need to change the volume # of one, probably the 7 issue series. Because of the way CV has it setup (the larger series has a cover date of 1/2016 and really SHOULD be listed as 2016 but CV is a horrible source of data with worse consistency than any could expect) this is displaying the store date as the year not the cover date.

For nearly every other publisher these situations don't exist, it's unique to Marvel/DC because they truly do not care about things like reader experience in the long run.

The original Library type would replace those silk series with each other each scan, same with Spider-Gwen. As well as any series named those not in those years.

I'm sure Joe would be open to suggestions on how to have kavita naturally differentiate but with our data source being such a giant turd it's really hard for him to have a path that works for everyone.

**Comment by wind-chant** [comment]
Thanks for the reply, I will modify one of the vloume
