### ISSUE TITLE
"Width Override" not included in Preferences

### ISSUE THREAD

**Issue by njdom24** [Kareadita/Kavita#3232]
### What happened?

I prefer, for manga, to scale the images to width, with a width override set. I can set width through the preferences settings, but no option exists for the override percentage, so I have to open the menu and set it every time I sit down to read.

From what I understand, this is currently not saved in the DB.

### What did you expect?

Have the "Width Override" option, that is available when reading, exposed through the preferences settings, to set globally.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
It is not planned to allow you to set a width override that persists and applies to all media on any device. It just doesn't make much sense as it's generally needed for some media, but not all and not the same for each imo. You can raise a Feature request, but it is unlikely to be implemented.

**Comment by njdom24** [comment]
I respect your decision.

I am a bit confused on the "some media" point, though. I find that, when reading manga, height scaling is too zoomed-out, width scaling is too zoomed-in. and original is inconsistent depending on the resolution of the source. The only way to get consistent zoom level on all of my manga is by using the width override feature.

I may look into this on my own in this case, because it's an necessary part of my routine every session.

**Comment by majora2007** [comment]
I would raise a feature request with this in it. I personally don't use the width override and for me height works perfectly on my tablet. If the community upvotes and comes forward, I am open to implementing. From my perspective, it seems like it would be tweaked on a case-by-case basis.

**Comment by eswiig** [comment]
I support having the option to set a global width override. you don't need to use it, but it's there as an option if you prefer it.
I can't read manga without width override, so I am thankful for the author to add this feature (even if it's not globally and has to be adjusted every time).

Maybe the reason why the dev has no issue with it is because he reads it on a tablet, I use it mainly on my PC with large or widescreen monitors.

edit: Yeah I tested it on my phone and tablet, the viewer experience is perfect without width override, but it's a different story on PC.

It's annoying having to adjust it every time I open a new comic. I wish I could set it to 50% globally, then adjust it manually on a per reading basis if I need to.
