### ISSUE TITLE
Light novel specials appears under both Books tab and Specials tab

### ISSUE THREAD

**Issue by newyorker123** [Kareadita/Kavita#3351]
### What happened?

In my light novel library, I followed the three instructions in the wiki to set the metadata for specials:

1. The filename MUST contain the SP markers (SP01, SP02, etc)
2. The internal metadata must have the calibre:series tag set to the Series it should be included in and a calibre:series_index of 0
3. The title tag must be set with the title of the Special

But the specials appears under both Books tab and Specials tab.

![image](https://github.com/user-attachments/assets/2fc3e3b1-4dde-490a-8493-43ebf05e8786)

![image](https://github.com/user-attachments/assets/771dcbe4-1591-4c3b-9f82-b4af544b5c33)

### What did you expect?

Specials should just appear under Specials tab, but not in Books tab.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment]
Okay I was able to reproduce this. This issue occurred because previously, I added this ability and 0 was the special number. When I rewrote the foundation of Kavita to support any issue number (like 0), I forgot to come back and update the documentation. 

100000 should be used as the series_index number to force grouping into a special. I'll update the documentation to reflect this.
