### ISSUE TITLE
Pdf ToC support

### ISSUE THREAD

**Issue by finzzz** [Kareadita/Kavita#548]
Hello, thanks for the app. This is the app I've been searching for, however I really need ToC when reading pdf. Would be great if it's supported in the future.

**Comment by majora2007** [comment]
How do you suppose I implement that? PDFs don't have rich metadata like that from what I've seen. Do you have any examples of applications that provide that outside of Adobe Reader?

**Comment by finzzz** [comment]
I'm not sure how you can implement that in c#, but this would be similar to this https://stackoverflow.com/questions/6157456/create-outlines-toc-for-existing-pdf-in-python#60631547 .  
My initial idea would be:  
1. User request book viewer
2. Process ToC
3. Serve it on webapp

**Comment by majora2007** [comment]
I'll take a look, but I wouldn't hold your breath for this. The PDF support
we have currently presents them as images. The reader for images doesn't
support any ToC because comics, mangas, or loose images don't have that
type of data.

It would be a total redesign of PDFs and due to them being pretty rough to
use already, it's not something I personally want to take up.

**Comment by majora2007** [comment]
Hello, I am closing this out. If you still want it, please move your feature request to https://feats.kavitareader.com. All feature requests should go there.
