### ISSUE TITLE
Investigate Pickle Rick's potential culture variant issue with parser

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#615]
Issue is occurring with matching or with parsing, in which decimal isn't being matched on. User machine is Italian locale and it is confirmed on non-Italian locale (Windows OS locale) that the parse happens correctly. 

What occurs is that "Deku&Bakugo-_Rising_v1_c1.1" will get parsed as Chapter 11 while on English systems, it will be parsed as Chapter 1.1

**Comment by majora2007** [comment]
I need a developer with a non-english OS locale to help test this out.

**Comment by ThePromidius** [comment]
I feel that this is what i had reported to you multiple times. I have spanish OS if it can help.

**Comment by majora2007** [comment]
Please take it up. Start with running the unit tests for Parsers

**Comment by ocgineer** [comment]
Just came across this and I thought it could've been something to do with us in Europe using a comma for decimal numbers and not a full stop (e.g.  $5.30 vs €5,30). As my System language is English (US) but my Country/Region (Locale) is set to Dutch I thought to test it. 

On my end it parses and shows up as Issue 1.1 (Comic) or Chapter 1.1 (Manga) in the series overview.
However, when I checked 'details' of the book it actually showed Chapter 11 instead of Chapter 1.1 in the details only.

I ran another test with another series and compared it with the same series on my server and it is different!

![maybe_also_locale_issue](https://user-images.githubusercontent.com/12483966/186910562-22208d4e-cb1a-4f8d-aaf9-508c4735984c.png)
The left is on my Linux Server in Docker, I believe everything is set to English. On the right is localhost on my Windows 11 system set to English US language with Dutch Region (locale).

**Comment by majora2007** [comment]
This is a big revelation, I looked a bit into it, but didn't see anything easy to implement for culture aware regex, since my regex uses things like `.` directly.

**Comment by ocgineer** [comment]
is it the regex though? Everything gets parsed correctly, the filename actually also uses a full stop, and shows in correct order in the chapters list. It looks more like a display issue where the UI tries to display 1.1 but expects 1,1 due to region? 

Database also has proper decimals
![image](https://user-images.githubusercontent.com/12483966/187100635-0de11a81-c756-4e91-acf9-c7ec68f86477.png)

**Comment by majora2007** [comment]
Oh that's interesting....because we just render it out as a string, so maybe browsers do something I'm not aware. Well this means that when I tackle localization, it will fix itself.

**Comment by majora2007** [comment]
I tried this out recently after localization and after I found some other issues with browser and OS locale, and cannot reproduce. I was using Sweden locale, which also uses `,` instead of `.`, but no luck. Since this issue is quite old and I haven't heard of it since, I'm going to close it out.
