### ISSUE TITLE
Book Settings reset to default after being modified and saved

### ISSUE THREAD

**Issue by zotabee** [Kareadita/Kavita#624]
**Describe the bug**
Some book settings reset instantly to default after being modified and saved

**To Reproduce**
1. Open Kavita from your browser
2. Go to "Libraries", select a book
3. Open any book till you see the content
4. Click on the hamburger menu which opens "Book Settings"
5. Customize the settings ex: increase Margin to "5%" and turn off the dark mode
6. Click on "Save"

**Expected behavior**.
It should keep the settings modified and save them.

In the case provided, once clicked on "Save", while prompting "User settings updated" in green at the bottom, it cancels all the modifications, it goes back to dark mode and margin to 0% (like the reset button I guess minus the notification).

Strangely, it happens both on desktop and on mobile but on desktop only the dark mode will revert, it seems to keep the other settings (line spacing and margin). While on mobile both margin and dark mode are getting reset while having  the "User settings updated" message. It seems fine with other settings (font size, line spacing, tap pagination).

**Smartphone (please complete the following information):**
 - Device: Samsung S20 5G
 - OS: Android 11
 - Browser: Chrome
 - Version: Version 94.0.4606.61

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 94.0.4606.71 (Official Build) (64-bit)
 
**Additional context**
Server is Debian 11, Kavita dockerized
Image : kizaing/kavita:latest
sha256:2bfa8d24c9d51e8eea4b4a1cf97d86d25fc8ea065028132b817b91cded367bf8  
Created on 2021-09-27 03:21:26

Could it be a rights/permissions issue? or did I miss something about settings modification.

Thanks a lot @majora2007 this project is awesome.

Regards,

zotabee

**Comment by majora2007** [comment]
Hello, this is by design. 

First, to help make it more clear, you do not have to press Save for the setting to take effect. The Save button is a way to save to your user preferences so you don't have to manually go to User Settings -> Reading and make modifications.

In the upcoming release, I have made a new toaster to inform the user that margin does not reflect on mobile. What this means is, on mobile, I enforce a 0% margin on load as usually, if left to normal margin (from desktop), then information would be cut off requiring more clicks to get it right.

So I put it at 0% to at least make the data readable. Again, if you want it to 5% you can open the menu and make that and close the menu, it instantly appears. But if you press save, I do save the setting, but revert what is being rendered at 0%.

I hope this makes it more clear. This is not a bug, but by design. Let me know if you have any suggestion

**Comment by zotabee** [comment]
Okay, I see. Thanks a lot !

Is it the same thing for the dark mode ? The behavior of the book setting seems strange too. It seems it always goes back to dark unless the site setting itself is set to false too. But if you put the dark mode of the website on then off, book setting is back to always off too. Unless I missed something.

**Comment by majora2007** [comment]
Let me take a look at this for you and get back to you if there is a bug or not.

**Comment by majora2007** [comment]
I have confirmed this is a bug, where dark mode gets reset when you hit Save. 

I created a new defect that you can watch here. It will be delivered with v0.4.7 (upcoming release). 

Thank you for reporting it. 

https://github.com/Kareadita/Kavita/issues/633

**Comment by zotabee** [comment]
Thank you so much! 🙌
