### ISSUE TITLE
Can I render content according to the folder directory structure?

### ISSUE THREAD

**Issue by akimolll** [Kareadita/Kavita#753]
I have more than 1000 comics. After importing, I found that there are only more than 600 comics. I found that they have been automatically divided into a collection one by one.

But Kavita recognition of some languages seems not intelligent enough, such as Japanese, Chinese and Korean. These collections are chaotic.I can't modify these contents according to Kavita's naming rules. The workload is a little heavy.

It is hoped that the folder view can be added. At least in the folder view, these contents are accurately classified.

The others are really great. Thank you for everything!❤️

**Comment by majora2007** [comment]
Hello, folder view is a very low priority item due to the way the database is constructed and the higher priority issues planned. Can you help me understand your library more to see if there is an alternative way to help you? 

"But Kavita recognition of some languages seems not intelligent enough, such as Japanese, Chinese and Korean. "

This is def something Kavita does not handle well. I would LOVE some filenames and characters to help me understand what is a volume, what is a chapter, etc.
