### ISSUE TITLE
Comic volumes being parsed as issues

### ISSUE THREAD

**Issue by therobbiedavis** [Kareadita/Kavita#764]
**Describe the bug**
For comic libraries, volume only archives (v01 not v01 #01) are being shown under issues instead of specials. If an issue can not be parsed from the file name, and it does not contain any of the specified "special" keyworks, we should assume it is a collection of issues and place it under specials.

**To Reproduce**
Test the parser against
"Batman v01 01" and "Batman v01"

**Expected behavior**
Batman v01 should be a special, Batman v01 01 should be an issue

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ALL
 - Browser: ALL
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: [ALL
 - OS: ALL
 - Browser: ALL
 - Version: All

**Comment by majora2007** [comment]
The problem I have with this is:
1. This is very different than how the Manga side works. It would be confusing to have it work differently between libraries. 
2. Specials show the full filename and do not bundle, so this would require pretty significant rework.

**Comment by LeeThompson** [comment]
As a software designer myself I offer the following comments.   These are just my opinions being offered as part of the conversation.

This project is supporting three distinct types of content: Manga, Comics and eBooks.   While there is *some* overlap, the requirements and naming conventions are not the same for these.     

For example: 
**eBooks**: Genre/author (and series if applicable, and sometimes sub-series) are important.   

**Manga**: Comics and Manga have more similarities but aren't 100% the same due to manga is usually published in collections (since the actual weekly publications have a lot of individual titles.   (Similar to if you only collected US comics as trade paperbacks.)   So naming/handling/etc should be split between them.

**Comics**:  Moreso than the others, has a scene with semi-standardized naming (I say semi because there are differences depending on the group or scanner).    (I also think Kavita has a way to go to handle different volumes here, I'd like to see a dropdown allowing you to jump between volumes instead it seems to be at the issue level making reading say volume 1 first, then volume 2 to be a pain in the ass.)

Obviously having these be separated does create coding challenges and makes things more messy but I think the goal should be to have Kavita as a reading app that works well for each of the major content types.

**Comment by majora2007** [comment]
> This project is supporting three distinct types of content: Manga, Comics and eBooks. While there is some overlap, the requirements and naming conventions are not the same for these.

This is not about supporting different naming conventions, but how the series detail page lays out code. Since I'm the sole developer, I want to keep the code as clean as possible and minimize maintenance. 

The issue here is that based on my experiences, scene will pack as volumes sometimes or other times package as just issues. So the question is, why should volumes be put into specials? See my 2 items and see where can we find a compromise without requiring huge refactors from me (which if that is the case, are unlikely to happen).

**Comment by majora2007** [comment]
Some other things to note on this issue, classifying as specials will require a huge refactor on getNext/getPrevious chapter which is used for continuous reading.
