### ISSUE TITLE
No cover images extracted from epubs

### ISSUE THREAD

**Issue by duckpuppy** [Kareadita/Kavita#838]
**Describe the bug**
No cover images were successfully extracted from any epubs during initial library scan or on a rescan. Additionally, if an image was present in the folder with the epub, it was not found as the cover (a common Calibre feature is to place the epub cover in the same folder as the epub itself, especially if a different one from the embedded cover is chosen).

I'm not sure if this is the result of scanning a Calibre library as the app doesn't seem to understand the layout of the library very well and tries to add a bunch of stuff that's typically part of the library layout, but not actually content (`.cache` folders, etc).

**To Reproduce**
1. Add Calibre library
2. Observe no images once scan is completed

**Expected behavior**
Cover element is extracted from epub

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser chrome
 - Version 0.4.9.1

**Comment by majora2007** [comment]
Can you please add logs? Cover extraction works on epubs, but many epubs from what I've seen are malformed and are missing a cover tag in the metadata. 

I know that Calibre doesn't write the tags to the actual epub file usually and stores them within it's own database, so that could be what's happening in your case. Logs will help me understand a lot more.

**Comment by majora2007** [comment]
I'm closing this issue. If you still have it on v0.5+, please comment with logs.
