### ISSUE TITLE
Book Reader Issues

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#928]
This is a dumping ground for NIGHTLY issues found with respect to the book reader.

**Comment by scare376** [comment]
There is an issue with scrolling. When you move onto another page in the ebook reader you need to click on the page to continue scrolling with the arrow keys. It seems like it might be a framing(probably the wrong word) issue because the bar at the top and tap pagination now covers the scroll bar.
This is from nightly 0.4.9.38.
![image_2022-01-12_180924](https://user-images.githubusercontent.com/2068470/149237491-d65b5be9-4654-4493-8eec-26144daaa168.png)
This is from stable 0.4.9.2
![image_2022-01-12_181007](https://user-images.githubusercontent.com/2068470/149237576-b7796e02-677c-400b-b8e1-b5fb0cb82e78.png)
